import {useEffect,useState} from 'react'
import type {BrowserAction,BrowserState,BrowserGrant} from '../shared/browser'
export function BrowserPage({sessionId}:{sessionId:string|null}){
 const [state,setState]=useState<BrowserState|null>(null),[grant,setGrant]=useState<BrowserGrant>({enabled:false,origins:[],interactOrigins:[],ports:[]}),[url,setUrl]=useState(''),[tab,setTab]=useState(''),[image,setImage]=useState(''),[text,setText]=useState(''),[selector,setSelector]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[snapshot,setSnapshot]=useState(''),[ports,setPorts]=useState<Record<string,string>>({})
 useEffect(()=>{let live=true;setState(null);setTab('');setImage('');if(sessionId)void window.unreal.browserState(sessionId).then(value=>{if(live){setState(value);setGrant(value.grant);setTab(value.tabs[0]?.id||'')}}).catch(reason=>{if(live)setError(String(reason))});return()=>{live=false}},[sessionId])
 const run=async(work:()=>Promise<unknown>)=>{if(!sessionId)return;setBusy(true);setError('');try{await work();setState(await window.unreal.browserState(sessionId))}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 const action=async(value:BrowserAction)=>{if(!sessionId)return;const result=await window.unreal.browserAction(sessionId,{tabId:tab||undefined,...value});if(result.tabId)setTab(result.tabId);if(result.image)setImage(`data:image/png;base64,${result.image}`);if(result.snapshot)setSnapshot(JSON.stringify(result,null,2));return result}
 if(!sessionId)return <div className="page-content"><h1>Browser</h1><p>Open a task before preparing its dedicated browser.</p></div>
 return <div className="page-content task-controls-page"><h1>Dedicated browser</h1><p>{state?.message} · Separate from your normal browser profile.</p>{error&&<p role="alert" className="error-inline">{error}</p>}
 <details><summary>Runtime and project access</summary><button disabled={busy||state?.installed} onClick={()=>void run(()=>window.unreal.browserInstall(sessionId))}>{state?.installed?'Chromium installed':'Prepare pinned Chromium runtime'}</button><label><input type="checkbox" checked={grant.enabled} onChange={e=>setGrant({...grant,enabled:e.target.checked})}/> Enable browser for this project</label><label>Observe origins · one per line<textarea value={grant.origins.join('\n')} onChange={e=>setGrant({...grant,origins:e.target.value.split('\n').filter(Boolean)})}/></label><label>Interaction origins · one per line<textarea value={grant.interactOrigins.join('\n')} onChange={e=>setGrant({...grant,interactOrigins:e.target.value.split('\n').filter(Boolean)})}/></label><label>Container preview ports · comma separated<input value={grant.ports.join(',')} onChange={e=>setGrant({...grant,ports:e.target.value.split(',').filter(Boolean).map(Number)})}/></label><p>Ports bind only to host loopback. Servers must listen on 0.0.0.0 inside the container. Port changes require idle work and a backend restart.</p><button disabled={busy} onClick={()=>void run(()=>window.unreal.browserConfigure(sessionId,grant))}>Review and save access</button></details>
 <div className="button-row"><button disabled={busy} onClick={()=>void run(async()=>setPorts(await window.unreal.previewPorts(sessionId)))}>Find project preview addresses</button>{Object.entries(ports).map(([port,address])=><button key={port} onClick={()=>setUrl(address)}>{port} → {address}</button>)}</div>
 <div className="button-row">{state?.tabs.map(item=><button aria-current={tab===item.id?'page':undefined} key={item.id} onClick={()=>{setTab(item.id);setUrl(item.url);setImage('')}}>{item.title||'Browser tab'}</button>)}</div>
 <form onSubmit={e=>{e.preventDefault();void run(()=>action({type:'navigate',url}))}}><label>URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="http://127.0.0.1:…"/></label><button disabled={busy||!url.trim()}>Open URL</button></form>
 <div className="button-row"><button disabled={busy||!tab} onClick={()=>void run(()=>action({type:'screenshot'}))}>Capture screenshot</button><button disabled={busy||!tab} onClick={()=>void run(()=>action({type:'snapshot'}))}>Inspect page and errors</button><button disabled={busy||!tab} onClick={()=>void run(()=>action({type:'takeover'}))}>Take over browser</button><button disabled={busy||!tab} onClick={()=>void run(async()=>{await action({type:'close'});setTab('');setImage('')})}>Close tab</button><button disabled={busy||!tab} onClick={()=>void run(()=>action({type:'viewport',width:390,height:844}))}>Phone viewport</button><button disabled={busy||!tab} onClick={()=>void run(()=>action({type:'viewport',width:1280,height:800}))}>Desktop viewport</button></div>
 {image&&<img className="browser-screenshot" src={image} alt="Current dedicated browser screenshot" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)*e.currentTarget.naturalWidth/rect.width,y=(e.clientY-rect.top)*e.currentTarget.naturalHeight/rect.height;void run(async()=>{await action({type:'click',x,y});await action({type:'screenshot'})})}}/>}
 <details><summary>Element interaction</summary><label>Selector<input value={selector} onChange={e=>setSelector(e.target.value)}/></label><label>Text<input value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!tab||!selector} onClick={()=>void run(()=>action({type:'fill',selector,text}))}>Fill input</button><button disabled={busy||!tab||!selector} onClick={()=>void run(()=>action({type:'click',selector}))}>Click element</button></details>{snapshot&&<pre>{snapshot}</pre>}</div>
}
