import {useEffect,useRef,useState} from 'react'
import {Monitor,MousePointer2,Pause,Play,Plus,RefreshCw,ShieldCheck,Square,Pin,X} from 'lucide-react'
import {motion} from 'motion/react'
import type {ComputerObservation,ComputerStatus,ComputerWindow} from '../shared/computer'
import {PaneDialog} from './PaneDialog'
import {ProgressIndicator} from './ProgressIndicator'
import {useReducedMotion} from './useReducedMotion'
import {spatial,instant} from './motion'
import {addImageAttachments,imageAttachments} from './image-drafts'
import {ExpressiveButton} from './ExpressiveButton'
import './computer.css'

const api=window.unreal
export function ComputerPage({sessionId,compact=false,onClose}:{sessionId?:string;compact?:boolean;onClose?:()=>void}){
 const [status,setStatus]=useState<ComputerStatus>(),[windows,setWindows]=useState<ComputerWindow[]>([]),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<ComputerObservation|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[control,setControl]=useState(false),[destination,setDestination]=useState(''),[handback,setHandback]=useState(0)
 const generation=useRef(0),previewGeneration=useRef(0),pending=useRef<number|undefined>(undefined),scope=useRef(0),currentSession=useRef(sessionId),reviewed=useRef<{sessionId:string;destination:string}|undefined>(undefined),reduced=useReducedMotion()
 if(currentSession.current!==sessionId){currentSession.current=sessionId;scope.current++;previewGeneration.current++;reviewed.current=undefined}
 useEffect(()=>{setReview(false);setBusy(false);setSelected([]);setPreview(null)},[sessionId])
 useEffect(()=>()=>{scope.current++;reviewed.current=undefined},[])
 useEffect(()=>{let alive=true,timer:ReturnType<typeof setTimeout>|undefined;const refresh=()=>{if(timer)clearTimeout(timer);timer=setTimeout(()=>{const token=++generation.current;void Promise.all([api.computerStatus(),api.computerLatest()]).then(([next,view])=>{if(alive&&token===generation.current){setStatus(next);if(view)setPreview(view);else if(next.state==='paused'||!next.grant)setPreview(null)}}).catch(reason=>{if(alive)setError(String(reason))})},50)};refresh();const off=api.onComputerChanged(refresh);return()=>{alive=false;generation.current++;previewGeneration.current++;off();if(timer)clearTimeout(timer)}},[sessionId])
 const run=async(work:(valid:()=>boolean)=>Promise<unknown>)=>{const token=scope.current;if(pending.current===token)return;pending.current=token;setBusy(true);setError('');const valid=()=>scope.current===token;try{await work(valid);if(valid()){const next=await api.computerStatus();if(valid())setStatus(next)}}catch(reason){if(valid())setError(String(reason))}finally{if(pending.current===token)pending.current=undefined;if(valid())setBusy(false)}}
 const discover=()=>run(async(valid)=>{const list=await api.computerWindows();if(!valid())return;setWindows(list);setSelected(value=>value.filter(id=>list.some(w=>w.id===id&&!w.blocked)))})
 const inspect=async(item:ComputerWindow)=>{const token=++previewGeneration.current;setError('');try{const view=await api.computerPreview(item.id);if(token===previewGeneration.current)setPreview(view)}catch(reason){if(token===previewGeneration.current)setError(String(reason))}}
 const reviewGrant=()=>run(async(valid)=>{if(!sessionId)throw Error('Create or select a conversation first');const config=await api.sessionConfig(sessionId);if(!valid())return;reviewed.current={sessionId,destination:JSON.stringify([config.provider,config.model,config.baseUrl||''])};setDestination(`${config.provider} · ${config.model}${config.baseUrl?` · ${config.baseUrl}`:''}`);setControl(config.mode!=='plan');setReview(true)})
 const grant=()=>run(async(valid)=>{if(!sessionId||reviewed.current?.sessionId!==sessionId)throw Error('Review access for this conversation first');await api.computerGrant(sessionId,selected,control,reviewed.current.destination);if(valid())setReview(false)})
 const resume=()=>run(async(valid)=>{await api.computerControl('resume');if(valid())setHandback(value=>value+1)})
 const title=compact?'Computer companion':'Computer'
 return <section className={`computer-page${compact?' computer-compact':''}`} aria-label={title}>
  <header className="computer-heading"><div><h2><Monitor size={22}/>{title}</h2><p>Selected windows. Visible control. Yours to take back.</p></div>{onClose&&<ExpressiveButton className="icon-button" onClick={onClose} aria-label="Close computer companion"><X size={18}/></ExpressiveButton>}</header>
  <div className="computer-scroll">
   <div className={`computer-state state-${status?.state||'loading'}`} role="status"><span className="computer-state-icon">{status?.state==='starting'||status?.activity?<ProgressIndicator label={status?.activity||'Preparing computer'}/>:<motion.span key={handback} initial={handback&&!reduced?{rotate:-16}:false} animate={{rotate:0}} transition={reduced?instant:spatial.fast}><MousePointer2 size={22}/></motion.span>}</span><div><strong>{!status?'Checking availability':status.state==='active'?'Task has access':status.state==='paused'?'You have control':status.state==='disabled'?'Computer is off':status.state==='starting'?'Preparing Windows helper':status.state==='unavailable'?'Computer needs attention':'Ready when you are'}</strong><p>{status?.message||'Loading saved preferences…'}</p></div></div>
   {status&&!status.enabled&&<div className="computer-onboarding"><h3>A little help with desktop work</h3><p>Use Windows apps with the current task. Choose exactly which windows it can see, and whether it can interact. Website work stays in Browser.</p><p>Window text and requested screenshots are sent to the task’s model. Password fields are concealed where Windows identifies them. Keep other sensitive content out of selected windows.</p><ExpressiveButton className="primary-button" disabled={busy} onClick={()=>run(()=>api.computerEnable(true))}><Plus size={16}/> Enable Computer</ExpressiveButton></div>}
   {!!status?.legacyConnections.length&&<details className="computer-migration"><summary>Review existing Windows add-on</summary><p>Adopting managed control withdraws the listed add-ons’ grants across projects. The add-on configuration is preserved.</p>{status.legacyConnections.map(item=><p key={item.id}>{item.name}</p>)}<ExpressiveButton className="secondary-button" disabled={busy} onClick={()=>run(()=>api.computerMigrate(status.legacyConnections.map(item=>item.id)))}>Adopt managed control</ExpressiveButton></details>}
   {status?.enabled&&<>
    <div className="computer-section-heading"><h3>Windows to share</h3><ExpressiveButton className="text-button" disabled={busy} onClick={discover}><RefreshCw size={15}/> Find windows</ExpressiveButton></div>
    {!windows.length&&<p className="muted-copy">Find open windows on this desktop. Elevated apps, personal browsers, and UnrealCode’s permission controls stay under your control.</p>}
    <div className="computer-windows">{windows.map(item=><article key={item.id} className={`computer-window${selected.includes(item.id)?' selected':''}`}><label><input type="checkbox" checked={selected.includes(item.id)} disabled={!!item.blocked||busy} onChange={event=>setSelected(value=>event.target.checked?[...value,item.id].slice(0,8):value.filter(id=>id!==item.id))}/><span><strong>{item.title||item.process}</strong><small>{item.process} {item.blocked?`· ${item.blocked}`:''}</small></span></label><ExpressiveButton className="text-button" disabled={!!item.blocked||busy} onClick={()=>void inspect(item)}>Preview</ExpressiveButton></article>)}</div>
    <ExpressiveButton className="primary-button computer-share" disabled={busy||!sessionId||!selected.length} onClick={reviewGrant}><ShieldCheck size={16}/> Review access{selected.length?` · ${selected.length}`:''}</ExpressiveButton>{!sessionId&&<p className="muted-copy">Select a conversation to grant access. Previewing a window yourself does not grant the agent access.</p>}
   </>}
   <div className="computer-preview" aria-label="Selected window preview">{preview?.preview?<img src={preview.preview} alt={`Preview of ${preview.window.title||preview.window.process}`}/>:<div><Monitor size={36}/><strong>{preview?'Accessibility observation':'Your selected window appears here'}</strong><p>Preview remains still while you read. New observations replace it.</p></div>}</div>
   {preview&&<div className="computer-evidence"><strong>{preview.window.title||preview.window.process}</strong><span>{new Date(preview.created).toLocaleTimeString()} · {preview.elements.length} elements</span>{preview.imageRef&&sessionId&&<ExpressiveButton className="text-button" onClick={()=>run(async()=>{if(imageAttachments(sessionId).length>=3)throw Error('Send or remove an existing attachment first');const image=await api.computerPin(sessionId,preview.imageRef!);addImageAttachments(sessionId,[image])})}><Pin size={14}/> Attach evidence to chat</ExpressiveButton>}<details><summary>Observed controls</summary><ul>{preview.elements.map(item=><li key={item.id}><strong>{item.role}</strong> {item.name||'(no accessible label)'}</li>)}</ul></details></div>}
   {status?.grant&&<div className="computer-owner"><strong>Owning task</strong><p>{status.grant.sessionId.slice(0,8)} · {status.grant.control?'Routine interaction':'Observation only'}</p><p>{status.grant.windows.map(w=>w.title||w.process).join(' · ')}</p><p className="muted-copy">External submissions, unknown actions and destructive changes require separate review. Screen content cannot grant permission.</p></div>}
   {!!status?.waiting.length&&<p>{status.waiting.length} task(s) are waiting for selected-window access. Input ownership is never transferred automatically.</p>}
   {error&&<p className="error-inline" role="alert">{error}</p>}
  </div>
  <footer className="computer-footer"><div>{status?.grant?<><ExpressiveButton className="secondary-button" disabled={busy||status.state==='paused'} onClick={()=>run(()=>api.computerControl('pause'))}><Pause size={15}/> Take over</ExpressiveButton><ExpressiveButton className="secondary-button" disabled={busy||status.state!=='paused'} onClick={resume}><Play size={15}/> Hand back</ExpressiveButton><ExpressiveButton className="secondary-button danger-button" onClick={()=>{void api.computerControl('stop').catch(reason=>setError(String(reason)))}}><Square size={14}/> Stop</ExpressiveButton></>:status?.enabled?<ExpressiveButton className="secondary-button" disabled={busy} onClick={()=>run(()=>api.computerEnable(false))}>Turn off Computer</ExpressiveButton>:null}</div><small>{status?.shortcut?'Emergency stop: Ctrl+Alt+Shift+.':'No active input grant'}</small></footer>
  {review&&<PaneDialog title="Review computer access" onClose={()=>setReview(false)}><p>Share these selected windows with <strong>{destination}</strong> for this conversation.</p><ul>{windows.filter(w=>selected.includes(w.id)).map(w=><li key={w.id}>{w.title||w.process}</li>)}</ul><label><input type="checkbox" checked={control} onChange={event=>setControl(event.target.checked)}/> Allow routine interaction</label><p>Mouse or keyboard input pauses the agent. Handback is always explicit. Existing sign-ins may expose private content in these windows.</p><p>Observation is permitted in Plan mode; interaction is not.</p><ExpressiveButton className="primary-button" disabled={busy} onClick={grant}>{busy?'Granting…':'Grant selected windows'}</ExpressiveButton>{error&&<p role="alert">{error}</p>}</PaneDialog>}
 </section>
}
