import {useEffect,useId,useLayoutEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {motion} from 'motion/react'
import {Check,Files,Search,X} from 'lucide-react'
import {expressive,instant,spatial} from './motion'
import {useReducedMotion} from './useReducedMotion'
import type {RepositoryHit} from '../shared/repository-context'
import type {SkillEntry} from '../shared/api'

export function ComposerContext({sessionId,prompt,onPrompt}:{sessionId?:string;prompt:string;onPrompt(value:string):void}){
 const [open,setOpen]=useState(false),[tab,setTab]=useState<'files'|'skills'>('files'),[query,setQuery]=useState(''),[hits,setHits]=useState<RepositoryHit[]>([]),[skills,setSkills]=useState<SkillEntry[]>([]),[attached,setAttached]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[fresh,setFresh]=useState('')
 const trigger=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLDialogElement>(null),generation=useRef(0),paths=useRef<string[]>([]),tail=useRef(Promise.resolve()),reduced=useReducedMotion(),id=useId()
 const promptRef=useRef(prompt);promptRef.current=prompt
 const close=()=>{setOpen(false);requestAnimationFrame(()=>trigger.current?.focus({preventScroll:true}))}
 useEffect(()=>{const owner=++generation.current;setOpen(false);setAttached([]);paths.current=[];setError('');setBusy(true);void window.unreal.contextView(sessionId||'draft').then(value=>{if(owner===generation.current){paths.current=value.selection.attached;setAttached(value.selection.attached)}}).catch(reason=>{if(owner===generation.current)setError(String(reason))}).finally(()=>{if(owner===generation.current)setBusy(false)});return()=>{generation.current++}},[sessionId])
 useEffect(()=>{const match=/(?:^|\s)@([^\s@]*)$/.exec(prompt);if(match){setOpen(true);setTab('files');setQuery(match[1])}},[prompt])
 useEffect(()=>{if(!open)return;let live=true;setLoading(true);setHits([]);setError('');const timer=setTimeout(()=>{void (tab==='skills'?window.unreal.listSkills().then(rows=>{if(live)setSkills(rows)}):query.trim()?window.unreal.repositorySearch(query,true).then(value=>{if(live)setHits(value.hits)}):Promise.resolve()).catch(reason=>{if(live)setError(String(reason))}).finally(()=>{if(live)setLoading(false)})},180);return()=>{live=false;clearTimeout(timer)}},[open,tab,query,sessionId])
 useLayoutEffect(()=>{if(!open)return;const element=dialog.current!;const place=()=>{const sheet=innerWidth<700;element.classList.toggle('sheet',sheet);if(sheet){element.style.removeProperty('left');element.style.removeProperty('top');return}const bounds=trigger.current!.getBoundingClientRect();element.style.left=Math.max(16,Math.min(bounds.left,innerWidth-element.offsetWidth-16))+'px';element.style.top=Math.max(16,Math.min(bounds.top-element.offsetHeight-8,innerHeight-element.offsetHeight-16))+'px'};element.showModal();place();const observer=new ResizeObserver(place);observer.observe(element);window.addEventListener('resize',place);return()=>{observer.disconnect();window.removeEventListener('resize',place);element.close()}},[open])
 const update=(path:string,remove=false)=>{const owner=generation.current,draft=prompt;setBusy(true);tail.current=tail.current.catch(()=>{}).then(async()=>{if(owner!==generation.current)return;const next=remove?paths.current.filter(x=>x!==path):[...new Set([...paths.current,path])];try{await window.unreal.updateContext(sessionId||'draft',{attached:next});if(owner!==generation.current)return;paths.current=next;setAttached(next);setFresh(remove?'':path);setError('');if(!remove&&promptRef.current===draft)onPrompt(draft.replace(/(?:^|\s)@[^\s@]*$/,''))}catch(reason){if(owner===generation.current)setError(String(reason))}finally{if(owner===generation.current)setBusy(false)}})}
 return <div className="composer-context">
  <button type="button" className="text-button composer-accessory" ref={trigger} aria-haspopup="dialog" aria-expanded={open} onClick={()=>{setQuery('');setOpen(true)}}><Files size={15}/><span>Files & skills{attached.length?' · '+attached.length:''}</span></button>
  {attached.length>0&&<div className="context-chips attached-files">{attached.map(path=><span key={path} className="attachment-chip" title={path}><span>{path.split('/').at(-1)}</span>{fresh===path&&<Check size={13} className={reduced?'':'attachment-confirm'}/>}<button className="icon-button" type="button" disabled={busy} aria-label={'Remove '+path} onClick={()=>update(path,true)}><X size={13}/></button></span>)}</div>}
  {!open&&error&&<p className="error-inline" role="alert">{error}</p>}
  {open&&createPortal(<motion.dialog ref={dialog} className="context-picker-dialog" aria-labelledby={id+'-title'} initial={reduced?false:{opacity:0,y:8,scale:.98}} animate={{opacity:1,y:0,scale:1}} transition={reduced?instant:expressive.panel} onCancel={e=>{e.preventDefault();close()}}>
   <header><h2 id={id+'-title'}>Add context</h2><button className="icon-button" type="button" aria-label="Close context picker" onClick={close}><X size={18}/></button></header>
   <div className="context-picker-tabs" role="tablist" aria-label="Context type">{(['files','skills'] as const).map(value=><button type="button" id={id+'-'+value+'-tab'} role="tab" aria-selected={tab===value} aria-controls={id+'-results'} tabIndex={tab===value?0:-1} key={value} onClick={()=>{setTab(value);setQuery('')}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=value==='files'?'skills':'files';setTab(next);setQuery('');document.getElementById(id+'-'+next+'-tab')?.focus()}}}>{tab===value&&<motion.span className="context-tab-selection" layoutId={id+'-tab'} transition={reduced?instant:spatial.fast}/>}<span>{value==='files'?'Files':'Skills'}</span></button>)}</div>
   <label className="context-picker-search" htmlFor={id+'-query'}>Search {tab}<span><Search size={16}/><input id={id+'-query'} autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==='files'?'Filename or path':'Skill name or description'}/></span></label>
   <div className="context-picker-results" id={id+'-results'} role="tabpanel" aria-labelledby={id+'-'+tab+'-tab'} aria-busy={loading}>
    {loading?<p role="status">Searching…</p>:tab==='files'?<>{[...new Map(hits.map(hit=>[hit.path,hit])).values()].map(hit=><button className="context-picker-result" type="button" key={hit.path} disabled={busy||attached.includes(hit.path)} onClick={()=>{update(hit.path)}}><Files size={17}/><span>{hit.path}</span>{attached.includes(hit.path)&&<Check size={16}/>}</button>)}{!hits.length&&<p>{query?'No included files match.':'Search for project files to attach.'}</p>}</>:<>{skills.filter(skill=>(skill.name+' '+skill.description).toLowerCase().includes(query.toLowerCase())).map(skill=><button type="button" className="context-picker-result" key={skill.name} onClick={()=>{onPrompt(prompt+'\n\nUse the selected project skill: '+skill.name+'. Read its current instructions using SkillUse.');close()}}><span><strong>{skill.name}</strong><small>{skill.description}</small></span></button>)}{!skills.length&&<p>No project skills found.</p>}</>}
   </div>{error&&<p role="alert" className="error-inline">{error}</p>}<footer><small>Files use current contents on send. Skills live in .harness/skills.</small><button type="button" className="secondary-button" onClick={close}>Done</button></footer>
  </motion.dialog>,document.body)}
 </div>
}
