import { FieldnoteReceipts } from './FieldnoteContext'
import { useEffect,useState,useRef } from 'react'
import type { ContextView } from '../shared/workflow'
import type { RepositorySearch,ContextSummary } from '../shared/repository-context'
export function ContextInspector({sessionId,onFile,onPreferences}:{sessionId?:string;onFile(path:string):void;onPreferences(patch:Partial<import('../shared/api').Settings>):Promise<void>}){
 const[context,setContext]=useState<ContextView|null>(null),[query,setQuery]=useState(''),[result,setResult]=useState<RepositorySearch|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const generation=useRef({id:sessionId,value:0});if(generation.current.id!==sessionId)generation.current={id:sessionId,value:generation.current.value+1}
 const[summaries,setSummaries]=useState<ContextSummary[]>([]),[automatic,setAutomatic]=useState(false)
 const refresh=async()=>{const version=generation.current.value;const [context,summaries,settings]=await Promise.all([window.unreal.contextView(sessionId||'draft'),sessionId?window.unreal.contextSummaries(sessionId):Promise.resolve([]),window.unreal.getSettings()]);if(version!==generation.current.value)return;setContext(context);setSummaries(summaries);setAutomatic(settings.autoCompaction)}
 useEffect(()=>{void refresh().catch(reason=>setError(String(reason)))},[sessionId])
 const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await work();await refresh()}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 return <div className="page-content context-inspector"><div className="page-heading"><div><h1>Context inspector</h1><p>See what is included, where it came from, and why.</p></div><button className="secondary-button" disabled={busy} onClick={()=>void run(refresh)}>Refresh</button></div>{error&&<p className="error-inline" role="alert">{error}</p>}
 <FieldnoteReceipts sessionId={sessionId}/>
 {context&&<><section className="settings-section"><h2>Selected context</h2><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{const source=await window.unreal.claudeInstructionsPreview();await window.unreal.claudeInstructionsImport(source.revision)})}>Review and import CLAUDE.md</button><p>Latest provider-reported input: {context.latestInput?.toLocaleString()??'unknown'} · verified limit: {context.contextLimit?.toLocaleString()??'unknown'}</p><p>Selected reference text estimate: {context.estimatedTokens.toLocaleString()} tokens.</p>{context.files.map(file=><div className="context-source" key={file.path}><button className="text-button" onClick={()=>onFile(file.path)}>{file.path}</button><span>{file.kind} · {file.included?`${file.bytes} bytes included`:file.reason}</span></div>)}{!context.files.length&&<p>No pinned or attached files.</p>}<details><summary>Persistent instructions</summary><pre>{context.instructions||'No additional project instructions.'}</pre></details><details><summary>Current user-reviewed summary</summary><pre>{context.selection.summary||'No summary selected.'}</pre></details><p>Exclusions: {context.selection.excluded.join(', ')||'None added'}. These are context preferences, not filesystem permissions. Edit them in Workflow → Context.</p></section></>}
 <section className="settings-section"><h2>Repository retrieval</h2><p>This search stays local. The agent’s RepositorySearch tool may ask the globally selected decision engine to rank focused results when project consent permits it.</p><div className="button-row"><input aria-label="Search repository context" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find source text or files"/><button className="primary-button" disabled={busy||!query.trim()} onClick={()=>void run(async()=>setResult(await window.unreal.repositorySearch(query)))}>Search sources</button></div>{result&&<><p>{result.status.files.toLocaleString()} files indexed · {(result.status.bytes/1048576).toFixed(1)} MB · {result.status.omitted} omitted · refreshed {result.status.refreshedAt?new Date(result.status.refreshedAt).toLocaleTimeString():'unknown'}</p>{result.hits.map(hit=><article className="context-result" key={`${hit.path}:${hit.line}`}><div className="button-row"><button className="text-button" onClick={()=>onFile(hit.path)}>{hit.path}:{hit.line}–{hit.endLine}</button><button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.updateContext(sessionId||'draft',{attached:[...new Set([...(context?.selection.attached||[]),hit.path])]}))}>Attach file</button><button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.updateContext(sessionId||'draft',{pinned:[...new Set([...(context?.selection.pinned||[]),hit.path])]}))}>Pin</button></div><small>{hit.reason} · revision {hit.revision.slice(0,12)}</small><pre>{hit.text}</pre></article>)}{!result.hits.length&&<p>No fresh matching excerpts.</p>}</>}</section>
 <section className="settings-section"><h2>Reversible compaction</h2><p>Create a model summary at an idle turn boundary. Original events remain available; restore full history whenever needed. Pinned files and current instructions stay in context.</p><label className="check-row"><input type="checkbox" checked={automatic} disabled={busy} onChange={e=>void run(()=>onPreferences({autoCompaction:e.target.checked}))}/> Automatically compact before the next turn at 80% of a verified context limit</label><p>Unknown context limits require manual compaction. Provider usage includes summary calls.</p><div className="button-row"><button className="primary-button" disabled={busy||!sessionId} onClick={()=>void run(()=>window.unreal.contextCompact(sessionId!))}>Create context summary</button><button className="secondary-button" disabled={busy||!sessionId||!summaries.some(item=>item.active)} onClick={()=>void run(()=>window.unreal.contextSummarySelect(sessionId!,''))}>Restore full history</button></div>{summaries.map(summary=><details key={summary.id}><summary>{summary.active?'Active · ':''}{new Date(summary.createdAt).toLocaleString()} · {summary.provider} / {summary.model}</summary><p>Source through event {summary.sourceSequence} · {summary.prefixItems} context items · fingerprint {summary.prefixHash.slice(0,12)}</p><p>Measured summary tokens: {summary.usage?.input??'unknown'} input, {summary.usage?.output??'unknown'} output.</p><pre>{summary.text}</pre><button className="secondary-button" disabled={busy||summary.active} onClick={()=>void run(()=>window.unreal.contextSummarySelect(sessionId!,summary.id))}>Use this version</button></details>)}</section>
 </div>
}
