import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import type { SessionInfo, Settings, Provider } from '../shared/api'
import type { DecisionTrace, EvaluationReport, EvaluationTask, ModelHealth } from '../shared/diagnostics'
const api = window.unreal

export function DiagnosticsPage({ settings, sessions, sessionId }: { settings: Settings; sessions: SessionInfo[]; sessionId: string | null }): ReactNode {
  const [tab, setTab] = useState('health'), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [provider, setProvider] = useState<Provider>(settings.provider === 'ollama' ? 'ollama' : 'openai-compatible')
  const [endpoint, setEndpoint] = useState(settings.baseUrl), [model, setModel] = useState(settings.model)
  const [health, setHealth] = useState<ModelHealth | null>(null)
  const [source, setSource] = useState(sessionId || ''), [traces, setTraces] = useState<DecisionTrace[]>([]), [notes, setNotes] = useState<Record<string, string>>({})
  const [tasks, setTasks] = useState<EvaluationTask[]>([{ prompt: '', criteria: '', testCommand: '' }])
  const [limit, setLimit] = useState(2), [timeout, setTimeoutMinutes] = useState(10), [reports, setReports] = useState<EvaluationReport[]>([])
  const run = async (work: () => Promise<unknown>): Promise<void> => { setBusy(true); setError(''); try { await work() } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const refresh = async (): Promise<void> => setReports(await api.evaluations())
  useEffect(() => { if (tab !== 'evaluations') return; void refresh().catch(reason => setError(String(reason))); const timer = setInterval(() => void refresh().catch(reason => setError(String(reason))), 2000); return () => clearInterval(timer) }, [tab])
  const loadTraces = async (): Promise<void> => { const values = await api.decisionTraces(source); setTraces(values); setNotes(Object.fromEntries(values.map(value => [value.id, value.override || '']))) }
  const editTask = (index: number, field: keyof EvaluationTask, value: string): void => setTasks(current => current.map((task, position) => position === index ? { ...task, [field]: value } : task))
  return <div className="page-content workflow-page"><div className="page-heading"><div><h1>Diagnostics</h1><p>Inspect runtime facts and compare explicitly selected tasks.</p></div></div>
    <div className="workflow-tabs" role="tablist">{[['health', 'Local model health'], ['decisions', 'Decision trace'], ['evaluations', 'Evaluations']].map(([id, title]) => <button className={tab === id ? 'active' : ''} role="tab" aria-selected={tab === id} key={id} onClick={() => setTab(id)}>{title}</button>)}</div>
    {error && <p className="error-text" role="alert">{error}</p>}
    {tab === 'health' && <section><h2>Local runtime</h2><div className="workflow-columns"><label>Provider<select value={provider} onChange={event => setProvider(event.target.value as Provider)}><option value="ollama">Ollama</option><option value="openai-compatible">Local compatible</option></select></label><label>Endpoint<input value={endpoint} onChange={event => setEndpoint(event.target.value)}/></label><label>Model<input value={model} onChange={event => setModel(event.target.value)} list="health-models"/></label><datalist id="health-models">{health?.models.map(value => <option key={value}>{value}</option>)}</datalist></div>
      <div className="review-actions"><button disabled={busy} onClick={() => void run(async () => setHealth(await api.modelHealth(provider, endpoint, model, false)))}>Check connectivity and models</button><button disabled={busy || !model.trim()} onClick={() => void run(async () => setHealth(await api.modelHealth(provider, endpoint, model, true)))}>Run small response test</button></div><p>The response test sends only “Reply with OK.” It can load the model and consume provider-reported tokens. It does not send project files.</p>
      {health && <div className="queue-card"><strong>{health.connected ? 'Connected' : 'Unavailable'}</strong><p>{health.message}</p><p>Checked {new Date(health.checkedAt).toLocaleString()} · {Math.round(health.latencyMs)} ms</p><p>Models: {health.models.join(', ') || 'None reported'}</p><p>Capabilities: {health.capabilities.join(', ') || 'Unknown'}</p><p>Context limit: {health.contextLimit?.toLocaleString() || 'Unknown'} {health.contextSource && `· ${health.contextSource}`}</p>{health.response && <><pre>{health.response}</pre><p>Measured input: {health.inputTokens ?? 'Unknown'} · output: {health.outputTokens ?? 'Unknown'}</p></>}</div>}
    </section>}
    {tab === 'decisions' && <section><h2>Recorded decisions</h2><div className="review-actions"><select aria-label="Decision trace session" value={source} onChange={event => { setSource(event.target.value); setTraces([]) }}><option value="">Choose a session</option>{sessions.map(session => <option value={session.id} key={session.id}>{session.title}</option>)}</select><button disabled={busy || !source} onClick={() => void run(loadTraces)}>Load decision trace</button></div><p>Probabilities are model judgments, not proof. Overrides are explicit user notes; disagreement is never inferred from later code changes.</p>{traces.map(trace => <article className="queue-card" key={trace.id}><strong>{trace.purpose}</strong><p>{trace.engine} · {trace.model} · {trace.durationMs} ms · {trace.recordedAt ? new Date(trace.recordedAt).toLocaleString() : 'Time unknown'}</p><p>Sources: {trace.sourceRefs.join(', ') || 'Not recorded'}</p><details><summary>Questions, evidence, probabilities, and measured usage</summary><pre>{JSON.stringify({ questions: trace.questions, evidence: trace.evidence, answers: trace.answers, usage: trace.usage }, null, 2)}</pre></details><label>Recorded user override<textarea value={notes[trace.id] || ''} onChange={event => setNotes({ ...notes, [trace.id]: event.target.value })} placeholder="No override recorded. Explain an explicit decision to proceed differently."/></label><button disabled={busy} onClick={() => void run(async () => { await api.decisionOverride(source, trace.id, notes[trace.id] || ''); await loadTraces() })}>Save override note</button></article>)}</section>}
    {tab === 'evaluations' && <section><h2>Compare decisions with the main model alone</h2><p>Runs use disposable worktrees from a clean committed revision and the same provider, model, task, and completion criteria. Actual provider usage is retained here separately from ordinary session totals. Account reports still include it.</p><p>Selected engine: {settings.decisionEngine} · Provider: {settings.provider} · Model: {settings.model}. Existing project consent applies. Laya may install its optional worker in the isolated runtime.</p>
      {tasks.map((task, index) => <div className="queue-card" key={index}><strong>Task {index + 1}</strong><label>Task prompt<textarea value={task.prompt} onChange={event => editTask(index, 'prompt', event.target.value)}/></label><label>Completion criteria<textarea value={task.criteria} onChange={event => editTask(index, 'criteria', event.target.value)}/></label><label>Verification command in the container (optional)<input value={task.testCommand} onChange={event => editTask(index, 'testCommand', event.target.value)}/></label>{tasks.length > 1 && <button onClick={() => setTasks(tasks.filter((_, position) => position !== index))}>Remove task</button>}</div>)}
      <div className="review-actions"><button disabled={tasks.length >= 10 || busy} onClick={() => { setTasks([...tasks, { prompt: '', criteria: '', testCommand: '' }]); setLimit(Math.max(limit, (tasks.length + 1) * 2)) }}>Add task</button><label>Run limit<input type="number" min={tasks.length * 2} max={20} value={limit} onChange={event => setLimit(Number(event.target.value))}/></label><label>Minutes per run<input type="number" min={1} max={30} value={timeout} onChange={event => setTimeoutMinutes(Number(event.target.value))}/></label><button className="primary-button" disabled={busy || settings.decisionEngine === 'off' || reports.some(report => report.state === 'running')} onClick={() => void run(async () => { await api.evaluationStart({ tasks, runLimit: limit, timeoutMinutes: timeout }); await refresh() })}>Start {tasks.length * 2} evaluation runs</button></div>
      <p>Results are observations. Wall time includes runtime setup and tests; cache warmth and provider variability can affect comparisons. No savings claim is inferred from decision-call latency. Review criteria against the recorded explanation, tests, and diff.</p>
      {reports.map(report => <article className="queue-card" key={report.id}><strong>{new Date(report.createdAt).toLocaleString()} · {report.state}</strong><p>{report.config.provider} / {report.config.model} · {report.engine} / {report.model} · {report.revision.slice(0, 12)}</p>{report.error && <p role="alert">{report.error}</p>}{report.state === 'running' && <button onClick={() => void run(() => api.evaluationCancel(report.id))}>Cancel evaluation</button>}{report.arms.some(arm => arm.worktree || arm.retainedVolume) && report.state !== 'running' && <button onClick={() => void run(async () => { await api.evaluationCleanup(report.id); await refresh() })}>Clean retained worktrees and storage</button>}<table><thead><tr><th>Task / mode</th><th>Result</th><th>Wall time</th><th>Measured tokens</th><th>Tests</th></tr></thead><tbody>{report.arms.map((arm, index) => <tr key={index}><td>{arm.task + 1} / {arm.decisions ? 'Decision enabled' : 'Main model only'}</td><td>{arm.state}</td><td>{arm.elapsedMs === undefined ? '—' : `${(arm.elapsedMs / 1000).toFixed(2)} s`}</td><td>{arm.usage ? `${arm.usage.input} in / ${arm.usage.output} out / ${arm.usage.cached} cached / ${arm.usage.decisionInput + arm.usage.decisionOutput} decision` : 'Not reported'}</td><td>{arm.tests ? `Exit ${arm.tests.exitCode}` : 'Not run'}</td></tr>)}</tbody></table><details><summary>Tasks, criteria, verification, changes, and retained paths</summary><pre>{JSON.stringify({ tasks: report.request.tasks, runs: report.arms }, null, 2)}</pre></details></article>)}
    </section>}
  </div>
}
