import { useEffect,useState } from 'react'
import type { GitHubIssue,GitHubReviewComment,GitHubCheck } from '../shared/github-workflow'
export function GitHubIntake({pullRequest}:{pullRequest:number|null}){
 const[issues,setIssues]=useState<GitHubIssue[]>([]),[selected,setSelected]=useState(0),[comments,setComments]=useState<GitHubReviewComment[]>([]),[checks,setChecks]=useState<GitHubCheck[]>([]),[logs,setLogs]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await work()}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 useEffect(()=>{let live=true;setComments([]);setChecks([]);setLogs('');if(pullRequest)void Promise.all([window.unreal.githubReviewComments(pullRequest),window.unreal.githubChecks(pullRequest)]).then(([nextComments,nextChecks])=>{if(live){setComments(nextComments);setChecks(nextChecks)}}).catch(reason=>{if(live)setError(String(reason))});return()=>{live=false}},[pullRequest])
 const intake=async(kind:'issue'|'review-comment',number:number,id?:number)=>{await window.unreal.githubIntake(kind,number,id);setNotice('Linked local task added. Open Workflow → Task queue to inspect it.')}
 const issue=issues.find(item=>item.number===selected)
 return <section className="settings-section github-intake"><h2>GitHub tasks and checks</h2><p>Choose an issue or review comment to create a linked local task. Remote submissions show a separate preview.</p>{error&&<p role="alert" className="error-inline">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="button-row"><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>setIssues(await window.unreal.githubIssues()))}>Load open issues</button><select aria-label="Select GitHub issue" value={selected} onChange={e=>setSelected(Number(e.target.value))}><option value={0}>Select an issue…</option>{issues.map(item=><option key={item.number} value={item.number}>#{item.number} {item.title}</option>)}</select></div>
 {issue&&<article><h3>#{issue.number} {issue.title}</h3><pre>{issue.body}</pre><button className="primary-button" disabled={busy} onClick={()=>void run(()=>intake('issue',issue.number))}>Create local issue task</button></article>}
 {pullRequest&&<><h3>Review comments on #{pullRequest}</h3>{comments.map(comment=><article className="context-result" key={comment.id}><strong>{comment.path}:{comment.line||1} · {comment.author}</strong><pre>{comment.body}</pre><button className="secondary-button" disabled={busy} onClick={()=>void run(()=>intake('review-comment',pullRequest,comment.id))}>Create local review task</button></article>)}{!comments.length&&<p>No inline review comments.</p>}<h3>Checks</h3>{checks.map((check,index)=><div className="github-list-row" key={`${check.url}:${index}`}><span>{check.name} · {check.state}</span>{['FAILURE','FAILED','TIMED_OUT','CANCELLED'].includes(check.state)&&<button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>setLogs(await window.unreal.githubFailureLogs(pullRequest,check.url)))}>Show failure log</button>}</div>)}{logs&&<details open><summary>Selected failure log · bounded and redacted</summary><pre>{logs}</pre></details>}</>}
 </section>
}
