import { useEffect,useState } from 'react'
import type { BackupPreview,RecoveryStatus,RetainedVolumeReport,StorageItem,UpdateState } from '../shared/recovery'
import { hasDirtyEditors } from './editor-buffers'
const api=window.unreal
const size=(bytes:number)=>bytes<1024**2?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1024**2).toFixed(1)} MiB`
export function RecoveryPanel({active=true}:{active?:boolean}){
 const [status,setStatus]=useState<RecoveryStatus>(),[update,setUpdate]=useState<UpdateState>(),[backup,setBackup]=useState<BackupPreview|null>(null),[rows,setRows]=useState<StorageItem[]>([]),[selected,setSelected]=useState<string[]>([]),[retained,setRetained]=useState<RetainedVolumeReport|null>(null),[support,setSupport]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[channel,setChannel]=useState<'stable'|'preview'>('stable')
 useEffect(()=>{if(!active)return;let disposed=false;const refresh=()=>void Promise.all([api.recoveryStatus(),api.updateStatus()]).then(([a,b])=>{if(!disposed){setStatus(a);setUpdate(b)}}).catch(()=>{});refresh();const timer=setInterval(refresh,1500);return()=>{disposed=true;clearInterval(timer)}},[active])
 const run=async(work:()=>Promise<unknown>,maintenance=false)=>{setNotice('');if(maintenance&&hasDirtyEditors()){setNotice('Save or close unsaved editor tabs before maintenance.');return}setBusy(true);try{const result=await work();if(typeof result==='string')setNotice(result)}catch(error){setNotice(String(error))}finally{setBusy(false)}}
 return <section className="settings-section wide-section recovery-panel" aria-label="Updates and recovery"><h2 id="settings-recovery" tabIndex={-1}>Updates and recovery</h2>
  {status?.waitingForDependency&&<div className="error-inline" role="status"><strong>Waiting for Docker</strong><p>{status.message}. Existing data has not been marked as damaged.</p><button disabled={busy} onClick={()=>void run(()=>api.recoveryAction('docker-open'))}>Open Docker Desktop</button><button disabled={busy} onClick={()=>void run(()=>api.recoveryRetry(),true)}>Retry checks</button></div>}
  {status?.migrationError&&<div role="alert" className="error-inline"><p>{status.migrationError}</p><button disabled={busy} onClick={()=>void run(()=>api.recoveryRetry(),true)}>Retry recovery checks</button></div>}
  <div className="recovery-grid"><div><h3>Application updates</h3><p>{update?.message||'Checking update support…'}</p><label>Release channel<select value={channel} onChange={e=>setChannel(e.target.value as 'stable'|'preview')} disabled={busy||update?.state==='downloading'}><option value="stable">Stable</option><option value="preview">Preview</option></select></label>
   <div className="button-row"><button disabled={busy||!update||update.state==='unavailable'||update.state==='downloading'} onClick={()=>void run(async()=>setUpdate(await api.updateCheck(channel)))}>Check for updates</button>{update?.state==='available'&&<button disabled={busy} onClick={()=>void run(async()=>setUpdate(await api.updateDownload()))}>Download {update.version}</button>}{update?.state==='downloading'&&<button onClick={()=>void api.updateCancel()}>Cancel download</button>}{update?.state==='ready'&&<button disabled={busy} onClick={()=>void run(()=>api.updateInstall(),true)}>Restart and install</button>}</div>{update?.state==='downloading'&&<progress aria-label="Update download" max={100} value={update.percent||0}/>}</div>
   <div><h3>Private recovery backup</h3><p>Save settings, history, workflow records, checkpoints and owned task files. Saved API keys and external logins are excluded. Conversation and project content may contain sensitive text: keep backups private.</p><p>Recovery uses this Windows profile and the original project paths. Model caches can be downloaded again.</p><div className="button-row"><button disabled={busy} onClick={()=>void run(()=>api.backupExport(),true)}>Export backup</button><button disabled={busy} onClick={()=>void run(async()=>setBackup(await api.backupPreview()))}>Preview restore</button></div>{status?.lastBackup&&<p className="storage-path">Last backup: {status.lastBackup}</p>}</div></div>
  {backup&&<div className="recovery-preview"><h3>Restore preview</h3><p>{backup.version} · {backup.files} files · {size(backup.bytes)} · {backup.volumes} saved-session volumes</p><ul>{backup.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul><button disabled={busy} onClick={()=>void run(()=>api.backupRestore(backup.id),true)}>Restore and restart…</button><button onClick={()=>setBackup(null)}>Cancel preview</button></div>}
  <h3>Storage</h3><p>Original events and unfinished task files are retained. Review exact paths before removing indexes, model caches or older completed backups.</p><button disabled={busy} onClick={()=>void run(async()=>{setRows(await api.storageList());setSelected([])})}>Inspect storage</button>{rows.length>0&&<><div className="storage-list">{rows.map(row=><label key={row.id}><input type="checkbox" disabled={!row.removable||busy} checked={selected.includes(row.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/><span><strong>{row.category} · {row.category==='recovery-volume'?'size unknown':size(row.bytes)}</strong><code>{row.path}</code><small>{row.reason}</small></span></label>)}</div><button disabled={busy||!selected.length} onClick={()=>void run(async()=>{await api.storageRemove(selected);setRows(await api.storageList());setSelected([])},true)}>Review selected cleanup…</button></>}
  <div className="retained-heading"><div><h3>Interrupted restore copies</h3><p>Inspect session volumes left by a stopped restore. Export saves session files for manual recovery; it is not a full app backup or a direct in-app import. Reattachment never replaces an existing project mapping.</p></div><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>setRetained(await api.retainedVolumes()))}>Inspect retained copies</button></div>
  {retained&&<div className="retained-list">{retained.items.length===0?<p className="muted-copy">No unregistered restore copies were found.</p>:retained.items.map(item=><article key={item.id} className="retained-card" aria-label={`Retained volume ${item.volume}`}><div><strong>{item.project||'Project unknown'}</strong><code>{item.volume}</code><small>{item.status.replaceAll('-',' ')} · {item.reason}</small></div><div className="button-row"><button className="secondary-button" disabled={busy||!item.exportable} aria-label={`Export session files from ${item.volume}`} onClick={()=>void run(async()=>{const path=await api.retainedVolumeExport(item.id);setRetained(await api.retainedVolumes());return path?`Exported retained sessions to ${path}`:undefined},true)}>Export session files</button><button className="secondary-button" disabled={busy||!item.attachable} aria-label={`Reattach ${item.volume}`} onClick={()=>void run(async()=>{const volume=await api.retainedVolumeAttach(item.id);setRetained(await api.retainedVolumes());return volume?`Reattached ${volume}. Trust the original project before opening its sessions.`:undefined},true)}>Reattach</button></div></article>)}{retained.additional>0&&<p className="muted-copy">{retained.additional} more retained identities need manual review; no action was taken on them.</p>}</div>}
  <h3>Support bundle</h3><p>Includes versions, runtime health and failure categories. Credentials, project names, file contents, conversations and raw errors are excluded. Review the exact JSON before export.</p><button disabled={busy} onClick={()=>void run(async()=>setSupport(await api.supportPreview()))}>Preview support bundle</button>{support&&<><pre className="support-preview">{support}</pre><button disabled={busy} onClick={()=>void run(()=>api.supportExport())}>Export this preview</button></>}
  {(notice||busy||status?.busy)&&<p role="status" className="notice">{notice||(status?.busy?status.message:'Working…')}</p>}
 </section>
}
