import { useEffect,useState } from 'react'
import type { BackupPreview,RecoveryStatus,StorageItem,UpdateState } from '../shared/recovery'
import { hasDirtyEditors } from './editor-buffers'
const api=window.unreal
const size=(bytes:number)=>bytes<1024**2?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1024**2).toFixed(1)} MiB`
export function RecoveryPanel(){
 const [status,setStatus]=useState<RecoveryStatus>(),[update,setUpdate]=useState<UpdateState>(),[backup,setBackup]=useState<BackupPreview|null>(null),[rows,setRows]=useState<StorageItem[]>([]),[selected,setSelected]=useState<string[]>([]),[support,setSupport]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[channel,setChannel]=useState<'stable'|'preview'>('stable')
 useEffect(()=>{let disposed=false;const refresh=()=>void Promise.all([api.recoveryStatus(),api.updateStatus()]).then(([a,b])=>{if(!disposed){setStatus(a);setUpdate(b)}}).catch(()=>{});refresh();const timer=setInterval(refresh,1500);return()=>{disposed=true;clearInterval(timer)}},[])
 const run=async(work:()=>Promise<unknown>,maintenance=false)=>{setNotice('');if(maintenance&&hasDirtyEditors()){setNotice('Save or close unsaved editor tabs before maintenance.');return}setBusy(true);try{const result=await work();if(typeof result==='string')setNotice(result)}catch(error){setNotice(String(error))}finally{setBusy(false)}}
 return <section className="settings-section wide-section recovery-panel" aria-label="Updates and recovery"><h2>Updates and recovery</h2>
  {status?.migrationError&&<div role="alert" className="error-inline"><p>{status.migrationError}</p><button disabled={busy} onClick={()=>void run(()=>api.recoveryRetry(),true)}>Retry recovery checks</button></div>}
  <div className="recovery-grid"><div><h3>Application updates</h3><p>{update?.message||'Checking update support…'}</p><label>Release channel<select value={channel} onChange={e=>setChannel(e.target.value as 'stable'|'preview')} disabled={busy||update?.state==='downloading'}><option value="stable">Stable</option><option value="preview">Preview</option></select></label>
   <div className="button-row"><button disabled={busy||!update||update.state==='unavailable'||update.state==='downloading'} onClick={()=>void run(async()=>setUpdate(await api.updateCheck(channel)))}>Check for updates</button>{update?.state==='available'&&<button disabled={busy} onClick={()=>void run(async()=>setUpdate(await api.updateDownload()))}>Download {update.version}</button>}{update?.state==='downloading'&&<button onClick={()=>void api.updateCancel()}>Cancel download</button>}{update?.state==='ready'&&<button disabled={busy} onClick={()=>void run(()=>api.updateInstall(),true)}>Restart and install</button>}</div>{update?.state==='downloading'&&<progress aria-label="Update download" max={100} value={update.percent||0}/>}</div>
   <div><h3>Private recovery backup</h3><p>Save settings, history, workflow records, checkpoints and owned task files. Saved API keys and external logins are excluded. Conversation and project content may contain sensitive text: keep backups private.</p><p>Recovery uses this Windows profile and the original project paths. Model caches can be downloaded again.</p><div className="button-row"><button disabled={busy} onClick={()=>void run(()=>api.backupExport(),true)}>Export backup</button><button disabled={busy} onClick={()=>void run(async()=>setBackup(await api.backupPreview()))}>Preview restore</button></div>{status?.lastBackup&&<p className="storage-path">Last backup: {status.lastBackup}</p>}</div></div>
  {backup&&<div className="recovery-preview"><h3>Restore preview</h3><p>{backup.version} · {backup.files} files · {size(backup.bytes)} · {backup.volumes} saved-session volumes</p><ul>{backup.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul><button disabled={busy} onClick={()=>void run(()=>api.backupRestore(backup.id),true)}>Restore and restart…</button><button onClick={()=>setBackup(null)}>Cancel preview</button></div>}
  <h3>Storage</h3><p>Original events and unfinished task files are retained. Review exact paths before removing indexes, model caches or older completed backups.</p><button disabled={busy} onClick={()=>void run(async()=>{setRows(await api.storageList());setSelected([])})}>Inspect storage</button>{rows.length>0&&<><div className="storage-list">{rows.map(row=><label key={row.id}><input type="checkbox" disabled={!row.removable||busy} checked={selected.includes(row.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/><span><strong>{row.category} · {size(row.bytes)}</strong><code>{row.path}</code><small>{row.reason}</small></span></label>)}</div><button disabled={busy||!selected.length} onClick={()=>void run(async()=>{await api.storageRemove(selected);setRows(await api.storageList());setSelected([])},true)}>Review selected cleanup…</button></>}
  <h3>Support bundle</h3><p>Includes versions, runtime health and failure categories. Credentials, project names, file contents, conversations and raw errors are excluded. Review the exact JSON before export.</p><button disabled={busy} onClick={()=>void run(async()=>setSupport(await api.supportPreview()))}>Preview support bundle</button>{support&&<><pre className="support-preview">{support}</pre><button disabled={busy} onClick={()=>void run(()=>api.supportExport())}>Export this preview</button></>}
  {(notice||busy||status?.busy)&&<p role="status" className="notice">{notice||(status?.busy?status.message:'Working…')}</p>}
 </section>
}
