import { useEffect,useState } from 'react'
import type { SessionInfo } from '../shared/api'
import { defaultWorkflowPresets,type WorkflowPresets,type WorkflowRun } from '../shared/verification'

export function SavedWorkflows({sessionId,sessions,onOpen}:{sessionId:string|null;sessions:SessionInfo[];onOpen(id:string):void}) {
 const [presets,setPresets]=useState<WorkflowPresets>(structuredClone(defaultWorkflowPresets)),[runs,setRuns]=useState<WorkflowRun[]>([]),[selected,setSelected]=useState(sessionId||''),[templateId,setTemplateId]=useState('review'),[profileId,setProfileId]=useState('')
 const [repair,setRepair]=useState(false),[repairId,setRepairId]=useState('fix'),[limit,setLimit]=useState(2),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[fullRun,setFullRun]=useState<WorkflowRun|null>(null)
 useEffect(()=>{let live=true,pending=false,timer:ReturnType<typeof setTimeout>|undefined;void window.unreal.workflowSettings().then(value=>{if(live){setPresets(value);setProfileId(value.profiles[0]?.id||'')}}).catch(reason=>setError(String(reason)));const refresh=()=>{if(pending)return;pending=true;void window.unreal.workflowRuns().then(value=>{if(live)setRuns(value)}).catch(reason=>{if(live)setError(String(reason))}).finally(()=>{pending=false})};refresh();const dispose=window.unreal.onWorkflowChanged(()=>{clearTimeout(timer);timer=setTimeout(refresh,150)});return()=>{live=false;clearTimeout(timer);dispose()}},[])
 const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await work();setRuns(await window.unreal.workflowRuns())}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 const template=presets.templates.find(item=>item.id===templateId),profile=presets.profiles.find(item=>item.id===profileId)
 const updateTemplate=(patch:Partial<NonNullable<typeof template>>)=>setPresets(value=>({...value,templates:value.templates.map(item=>item.id===templateId?{...item,...patch}:item)}))
 const updateProfile=(patch:Partial<NonNullable<typeof profile>>)=>setPresets(value=>({...value,profiles:value.profiles.map(item=>item.id===profileId?{...item,...patch}:item)}))
 return <section className="saved-workflows"><h2>Saved workflows</h2><p>Templates use the selected session’s current provider and permissions. Verification commands run in its container after an explicit preview.</p>
 {error&&<p className="error-inline" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <label>Task session<select aria-label="Workflow task session" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a task</option>{sessions.map(session=><option key={session.id} value={session.id}>{session.title}</option>)}</select></label>
 <div className="saved-workflow-columns"><section className="settings-section"><h3>Review, test and fix templates</h3><label>Template<select value={templateId} onChange={event=>setTemplateId(event.target.value)}>{presets.templates.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{template&&<><label>Template name<input value={template.name} onChange={event=>updateTemplate({name:event.target.value})}/></label><label>Kind<select value={template.kind} onChange={event=>updateTemplate({kind:event.target.value as typeof template.kind})}><option value="review">Review</option><option value="test">Test</option><option value="fix">Fix</option></select></label><label>Instructions<textarea aria-label="Workflow template instructions" value={template.prompt} onChange={event=>updateTemplate({prompt:event.target.value})}/></label></>}
 <div className="button-row"><button className="secondary-button" disabled={busy} onClick={()=>{const id=crypto.randomUUID();setPresets(value=>({...value,templates:[...value.templates,{id,name:'New review',kind:'review',prompt:'Review the selected task.'}]}));setTemplateId(id)}}>New template</button><button className="secondary-button" disabled={busy||!template} onClick={()=>{setPresets(value=>({...value,templates:value.templates.filter(item=>item.id!==templateId)}));setTemplateId('')}}>Remove template</button><button className="primary-button" disabled={busy||!selected||!template} onClick={()=>void run(async()=>{await window.unreal.workflowSave(presets);await window.unreal.workflowTemplate(selected,templateId);onOpen(selected)})}>Save and send template</button></div></section>
 <section className="settings-section"><h3>Named verification profiles</h3><label>Profile<select aria-label="Verification profile" value={profileId} onChange={event=>setProfileId(event.target.value)}><option value="">Choose a profile</option>{presets.profiles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{profile&&<><label>Profile name<input value={profile.name} onChange={event=>updateProfile({name:event.target.value})}/></label><label>Container command<textarea aria-label="Verification command" value={profile.command} onChange={event=>updateProfile({command:event.target.value})}/></label><label>Timeout per run (seconds)<input type="number" min={1} max={600} value={profile.timeoutSeconds} onChange={event=>updateProfile({timeoutSeconds:Number(event.target.value)})}/></label></>}
 <div className="button-row"><button className="secondary-button" disabled={busy} onClick={()=>{const id=crypto.randomUUID();setPresets(value=>({...value,profiles:[...value.profiles,{id,name:'Project tests',command:'',timeoutSeconds:120}]}));setProfileId(id)}}>New verification profile</button><button className="secondary-button" disabled={busy||!profile} onClick={()=>{setPresets(value=>({...value,profiles:value.profiles.filter(item=>item.id!==profileId)}));setProfileId('')}}>Remove profile</button></div>
 <label className="check-row"><input type="checkbox" checked={repair} onChange={event=>setRepair(event.target.checked)}/> Allow a bounded model repair loop after failure</label>{repair&&<><label>Fix template<select value={repairId} onChange={event=>setRepairId(event.target.value)}>{presets.templates.filter(item=>item.kind==='fix').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Maximum repair attempts<input type="number" min={1} max={5} value={limit} onChange={event=>setLimit(Number(event.target.value))}/></label><p>At most {limit} repairs and {limit+1} command runs. Each repair retains the session’s existing approval rules.</p></>}
 {profile&&<><pre className="verification-command-preview">{profile.command||'Enter a command to preview.'}</pre><button className="primary-button" disabled={busy||!selected||!profile.command.trim()} onClick={()=>void run(async()=>{await window.unreal.workflowSave(presets);await window.unreal.workflowStart(selected,profileId,repair?repairId:undefined,repair?limit:0);setNotice('Workflow started. Open its task for any required approvals or input.')})}>Preview and start verification</button></>}
 </section></div><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{await window.unreal.workflowSave(presets);setNotice('Templates and profiles saved for this project.')})}>Save templates and profiles</button>
 <h3>Verification history</h3>{!runs.length&&<p>No verification runs yet.</p>}{[...runs].reverse().map(item=><article className="queue-card" key={item.id}><strong>{item.profile.name} · {item.state}</strong><p>{new Date(item.createdAt).toLocaleString()} · {item.repairsStarted}/{item.maxRepairAttempts} repair attempts</p>{item.message&&<p>{item.message}</p>}{item.attempts.map((attempt,index)=><details key={attempt.id}><summary>Check {index+1} · exit {attempt.exitCode} · {(attempt.durationMs/1000).toFixed(2)} seconds</summary><pre>{attempt.output}</pre><small>Preview limited to 2,000 characters. Full recorded output is available below.</small></details>)}<div className="button-row"><button className="secondary-button" onClick={()=>onOpen(item.sessionId)}>Open task</button><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>setFullRun(await window.unreal.workflowRun(item.id)))}>Open full results</button>{['running','repairing'].includes(item.state)?<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.workflowCancel(item.id))}>Cancel workflow</button>:<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.workflowRemove(item.id))}>Remove record</button>}</div></article>)}
 {fullRun&&<section className="settings-section"><div className="button-row"><h3>{fullRun.profile.name} · recorded results</h3><button className="secondary-button" onClick={()=>setFullRun(null)}>Close results</button></div>{fullRun.attempts.map((attempt,index)=><section key={attempt.id}><h4>Check {index+1} · exit {attempt.exitCode}</h4><pre>{attempt.command}</pre><pre>{attempt.output||'(No output)'}</pre></section>)}</section>}
 </section>
}
