import {useEffect,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,RotateCw,Search,Square,Plus,X,ShieldCheck,Hand} from 'lucide-react'
import type {BrowserGrant,SharedBrowserCommand,SharedBrowserState} from '../shared/browser'
import {BrowserPage as LegacyBrowserPage} from './BrowserPage'

const empty:BrowserGrant={enabled:false,origins:[],interactOrigins:[],ports:[]}
export function SharedBrowserPage({project,sessionId}:{project:string;sessionId:string|null}){
 const [state,setState]=useState<SharedBrowserState>(),[grant,setGrant]=useState<BrowserGrant>(empty),[url,setUrl]=useState(''),[find,setFind]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[legacy,setLegacy]=useState(false)
 const viewport=useRef<HTMLDivElement>(null),generation=useRef(0)
 useEffect(()=>{const version=++generation.current;setState(undefined);setGrant(empty);setUrl('');setError('');void window.unreal.sharedBrowserState().then(value=>{if(version!==generation.current)return;setState(value);setGrant(value.grant);setUrl(value.tabs.find(tab=>tab.id===value.activeId)?.url||'')}).catch(reason=>{if(version===generation.current)setError(String(reason))});const dispose=window.unreal.onSharedBrowserChanged(changed=>{if(changed===project)void window.unreal.sharedBrowserState().then(value=>{if(version!==generation.current)return;setState(value);setUrl(current=>current||value.tabs.find(tab=>tab.id===value.activeId)?.url||'')}).catch(()=>{})});return()=>{generation.current++;dispose();void window.unreal.sharedBrowserHide()}},[project])
 const active=state?.tabs.find(tab=>tab.id===state.activeId)
 useEffect(()=>{const element=viewport.current;if(!element)return;const update=()=>{const box=element.getBoundingClientRect();if(state?.activeId&&box.width>100&&box.height>80)void window.unreal.sharedBrowserShow(state.activeId,{x:box.x,y:box.y,width:box.width,height:box.height}).catch(reason=>setError(String(reason)))};const observer=new ResizeObserver(update);observer.observe(element);window.addEventListener('resize',update);update();return()=>{observer.disconnect();window.removeEventListener('resize',update)}},[state?.activeId,legacy])
 const command=async(value:SharedBrowserCommand)=>{setBusy(true);setError('');try{const next=await window.unreal.sharedBrowserCommand(value);setState(next);const selected=next.tabs.find(tab=>tab.id===next.activeId);if(selected&&['select','new','navigate','back','forward'].includes(value.type))setUrl(selected.url)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
 const save=async()=>{setBusy(true);setError('');try{await window.unreal.sharedBrowserConfigure(grant);setState(await window.unreal.sharedBrowserState())}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
 const navigate=()=>void command({type:active?'navigate':'new',tabId:active?.id,url:url.includes('://')?url:`https://${url}`})
 return <div className="page-content shared-browser-page"><div className="page-heading"><div><h1>Browser</h1><p>Browse normally in this project. Hand a tab to the agent only after granting its exact origins.</p></div></div>
  <div className="shared-browser-tabs" role="tablist">{state?.tabs.map(tab=><div className="shared-browser-tab" key={tab.id}><button role="tab" aria-selected={tab.id===state.activeId} className={tab.id===state.activeId?'selected':''} onClick={()=>void command({type:'select',tabId:tab.id})} title={tab.url}>{tab.title||tab.url||'New tab'}{tab.control==='agent'&&<ShieldCheck size={13}/>}</button><button aria-label={`Close ${tab.title||'browser tab'}`} onClick={()=>void command({type:'close',tabId:tab.id})}><X size={14}/></button></div>)}<button aria-label="New browser tab" onClick={()=>void command({type:'new',url:'https://example.com'})}><Plus size={17}/></button></div>
  <div className="shared-browser-toolbar"><button aria-label="Back" disabled={!active?.canGoBack} onClick={()=>void command({type:'back',tabId:active?.id})}><ArrowLeft size={17}/></button><button aria-label="Forward" disabled={!active?.canGoForward} onClick={()=>void command({type:'forward',tabId:active?.id})}><ArrowRight size={17}/></button><button aria-label={active?.loading?'Stop loading':'Reload'} disabled={!active} onClick={()=>void command({type:active?.loading?'stop':'reload',tabId:active?.id})}>{active?.loading?<Square size={16}/>:<RotateCw size={17}/>}</button><form onSubmit={event=>{event.preventDefault();navigate()}}><input aria-label="Browser address" value={url} onChange={event=>setUrl(event.target.value)} onFocus={event=>event.currentTarget.select()} placeholder="Search or enter an address"/><button disabled={!url.trim()||busy}>Go</button></form><div className="browser-find"><Search size={15}/><input aria-label="Find on page" value={find} onChange={event=>{setFind(event.target.value);if(active)void command({type:'find',tabId:active.id,query:event.target.value})}} placeholder="Find"/></div><select aria-label="Browser zoom" value={active?.zoom||1} disabled={!active} onChange={event=>void command({type:'zoom',tabId:active?.id,zoom:Number(event.target.value)})}>{[.5,.75,1,1.25,1.5,2,3].map(value=><option key={value} value={value}>{Math.round(value*100)}%</option>)}</select></div>
  <div className="shared-browser-access"><span>{active?.control==='agent'?'Agent may use this tab within its origin grants':'You control this tab'}</span>{active&&<button className="secondary-button" onClick={()=>void command({type:active.control==='agent'?'takeover':'handback',tabId:active.id})}><Hand size={15}/>{active.control==='agent'?'Take over':'Hand to agent'}</button>}<details><summary>Agent origin grants</summary><p>Observation lets the agent read a signed-in page. Interaction also lets it act there; ordinary user browsing needs neither grant.</p><label><input type="checkbox" checked={grant.enabled} onChange={event=>setGrant({...grant,enabled:event.target.checked})}/> Enable agent browser tools</label><label>Observe origins, one per line<textarea value={grant.origins.join('\n')} onChange={event=>setGrant({...grant,origins:event.target.value.split('\n').map(value=>value.trim()).filter(Boolean)})}/></label><label>Interact origins, one per line<textarea value={grant.interactOrigins.join('\n')} onChange={event=>setGrant({...grant,interactOrigins:event.target.value.split('\n').map(value=>value.trim()).filter(Boolean)})}/></label><label>Allow Jev cloud page analysis, one origin per line<textarea value={(grant.cloudOrigins||[]).join('\n')} onChange={event=>setGrant({...grant,cloudOrigins:event.target.value.split('\n').map(value=>value.trim()).filter(Boolean)})}/></label><button className="primary-button" disabled={busy} onClick={()=>void save()}>Review and save grants</button></details></div>
  {error&&<p role="alert" className="error-inline">{error}</p>}
  <div className="shared-browser-viewport" ref={viewport} role="region" aria-label="Live project browser">{!active&&<p>Enter an address to open your first tab.</p>}</div>
  {sessionId&&<details className="legacy-browser"><summary onClick={()=>setLegacy(value=>!value)}>Legacy isolated browser recovery</summary>{legacy&&<LegacyBrowserPage sessionId={sessionId}/>}</details>}
 </div>
}
