import { useEffect,useRef,useState } from 'react'
import type { ReactNode } from 'react'
import { motion } from 'motion/react'
import { ProgressIndicator } from './ProgressIndicator'
import { useReducedMotion } from './useReducedMotion'
import { spatial } from './motion'
import { defaultTeamOptions,type TeamOptions,type TeamView,type SpecialistRole } from '../shared/teams'
import type { WorkspacePreview } from '../shared/task-workspaces'

function TeamTab({active,onClick,children}:{active:boolean;onClick():void;children:ReactNode}) {
 const reduced=useReducedMotion()
 return <motion.button className="secondary-button" aria-current={active?'page':undefined} onClick={onClick} animate={{borderRadius:active?14:7}} transition={reduced?{duration:0}:spatial.fast}>{children}</motion.button>
}

function useTeam(sessionId?:string) {
 const [team,setTeam]=useState<TeamView|null>(null),[error,setError]=useState('')
 useEffect(()=>{let live=true,pending=false,timer:ReturnType<typeof setTimeout>|undefined;setTeam(null);setError('');const refresh=()=>{if(!sessionId||pending)return;pending=true;void window.unreal.teamView(sessionId).then(value=>{if(live)setTeam(value)}).catch(reason=>{if(live)setError(String(reason))}).finally(()=>{pending=false})};refresh();const dispose=window.unreal.onWorkflowChanged(()=>{clearTimeout(timer);timer=setTimeout(refresh,150)});return()=>{live=false;clearTimeout(timer);dispose()}},[sessionId])
 return{team,error}
}
export { TaskTeamControls } from './TaskOptions'
export function TaskTeamRail({sessionId,onOpen}:{sessionId?:string;onOpen(id:string):void}) {
 const{team,error:loadError}=useTeam(sessionId),[error,setError]=useState(''),[busy,setBusy]=useState(false),[role,setRole]=useState<SpecialistRole>('explorer'),[assignment,setAssignment]=useState(''),[ownership,setOwnership]=useState(''),[steering,setSteering]=useState<Record<string,string>>({})
 const[preview,setPreview]=useState<WorkspacePreview|null>(null),[reviewed,setReviewed]=useState(''),[selected,setSelected]=useState<string[]>([]),dialog=useRef<HTMLDialogElement>(null),[notice,setNotice]=useState('')
 useEffect(()=>{setPreview(null);setError('');setNotice('')},[sessionId])
 useEffect(()=>{if(preview)dialog.current?.showModal();else dialog.current?.close()},[preview])
 if(!team)return loadError?<p role="alert">{loadError}</p>:null
 const parent=team.parentSessionId
 const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await work()}catch(reason){setError(String(reason))}finally{setBusy(false)}}
 const active=(state:string)=>['queued','starting','running','waiting_input'].includes(state)
 return <section className="context-card team-rail" aria-label="Agent team (subagents)"><h3>Agent team (subagents) <small>{team.workers.filter(worker=>active(worker.state)).length} active · {team.globalActiveWorkers}/4 global</small></h3>
 <div className="team-worker-tabs" role="navigation" aria-label="Task chats"><TeamTab active={sessionId===parent} onClick={()=>onOpen(parent)}>Parent</TeamTab>{team.workers.filter(worker=>worker.sessionId).map((worker,index)=><TeamTab key={worker.id} active={sessionId===worker.sessionId} onClick={()=>onOpen(worker.sessionId!)}>{index+1} · {worker.role}</TeamTab>)}</div>
 <p>{team.paused?team.message||'Paused':`${team.parentState} · ${team.modelRequests} model requests · ${Math.floor(team.elapsedMs/60000)} active min`}</p>
 <dl className="team-usage"><div><dt>Parent tokens</dt><dd>{(team.parentUsage.input+team.parentUsage.output+team.parentUsage.decisionInput+team.parentUsage.decisionOutput).toLocaleString()}</dd></div><div><dt>Specialist tokens</dt><dd>{(team.workerUsage.input+team.workerUsage.output+team.workerUsage.decisionInput+team.workerUsage.decisionOutput).toLocaleString()}</dd></div><div><dt>Task tokens</dt><dd>{(team.totalUsage.input+team.totalUsage.output+team.totalUsage.decisionInput+team.totalUsage.decisionOutput).toLocaleString()}</dd></div></dl>
 <div className="button-row">{team.paused&&<button className="primary-button" disabled={busy} onClick={()=>void run(async()=>{await window.unreal.teamResume(parent);await window.unreal.openSession(parent)})}>Resume parent</button>}<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.teamStop(parent))}>Stop all</button></div>
 {(error||loadError)&&<p className="error-inline" role="alert">{error||loadError}</p>}{notice&&<p role="status">{notice}</p>}
 {team.workers.map(worker=><details className="team-worker" key={worker.id}><summary><ProgressIndicator animate={false} state={worker.state==='running'||worker.state==='starting'?'running':worker.state==='waiting_input'?'waiting':worker.state==='failed'?'error':worker.state==='completed'?'success':'idle'}/>{worker.role} · {worker.state}<small>{worker.assignment.slice(0,80)}</small></summary><p>{worker.assignment}</p><p>Ownership: {worker.ownership.join(', ')}</p><small>Base checkpoint: {worker.snapshot||'Preparing'}{worker.omitted&&Object.keys(worker.omitted).length>0&&` · ${Object.keys(worker.omitted).length} omitted`}</small>{worker.omitted&&Object.keys(worker.omitted).length>0&&<pre>{JSON.stringify(worker.omitted,null,2)}</pre>}{worker.message&&<p>{worker.message}</p>}{worker.findings&&<pre>{worker.findings}</pre>}
 <div className="button-row">{worker.sessionId&&<button className="secondary-button" onClick={()=>onOpen(worker.sessionId!)}>Open chat & verification</button>}{active(worker.state)?<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.teamWorkerAction(parent,worker.id,'cancel'))}>Stop specialist</button>:<><button className="secondary-button" disabled={busy||team.paused||(!worker.sessionId&&worker.state!=='interrupted')} onClick={()=>void run(()=>window.unreal.teamWorkerAction(parent,worker.id,'resume'))}>Resume specialist</button><button className="secondary-button" disabled={busy||!worker.workspaceId} onClick={()=>void run(async()=>{setPreview(await window.unreal.teamPreview(parent,worker.id));setReviewed(worker.id);setSelected([])})}>Review changes</button><button className="secondary-button" disabled={busy} onClick={()=>void run(()=>window.unreal.teamWorkerAction(parent,worker.id,'retain'))}>Retain separately</button></>}</div>
 {active(worker.state)&&worker.state!=='starting'&&<form onSubmit={event=>{event.preventDefault();void run(async()=>{await window.unreal.teamWorkerAction(parent,worker.id,active(worker.state)?'steer':'followup',steering[worker.id]||'');setSteering(value=>({...value,[worker.id]:''}))})}}><label>Steer this specialist<textarea value={steering[worker.id]||''} onChange={event=>setSteering(value=>({...value,[worker.id]:event.target.value}))}/></label><button className="secondary-button" disabled={busy||!(steering[worker.id]||'').trim()}>Send steering</button></form>}
 </details>)}
 {team.options.allowSpecialists&&sessionId===parent&&<details><summary>Assign a subagent</summary><label>Role<select value={role} onChange={event=>setRole(event.target.value as SpecialistRole)}><option value="explorer">Explorer · read only</option><option value="implementer">Implementer</option><option value="reviewer">Reviewer · read only</option><option value="browser-tester">Browser tester</option></select></label><label>Assignment<textarea value={assignment} onChange={event=>setAssignment(event.target.value)}/></label><label>Owned files or responsibility (one per line)<textarea value={ownership} onChange={event=>setOwnership(event.target.value)}/></label><button className="primary-button" disabled={busy||team.paused||!assignment.trim()||!ownership.trim()} onClick={()=>void run(async()=>{await window.unreal.teamDispatch(parent,{role,assignment,ownership:ownership.split('\n').map(value=>value.trim()).filter(Boolean)});setAssignment('');setOwnership('')})}>Start subagent</button></details>}
 <dialog ref={dialog} className="team-review-dialog" aria-labelledby="team-review-title" onCancel={()=>setPreview(null)}>{preview&&<><h2 id="team-review-title">Review specialist changes</h2><p>Integrate selected files into the parent workspace. Conflicting later edits are blocked; a recovery checkpoint is saved first.</p><p>{preview.workspace.path}</p>{Object.entries(preview.omitted).map(([path,reason])=><p key={path}>{path}: not captured — {reason}</p>)}{preview.changes.map(file=><details className="workspace-change" key={file.path}><summary><label><input type="checkbox" disabled={file.conflict||busy} checked={selected.includes(file.path)} onChange={event=>setSelected(value=>event.target.checked?[...value,file.path]:value.filter(path=>path!==file.path))}/>{file.path} · {file.change}{file.conflict?' · conflict':''}</label></summary>{file.binary?<p>Binary file · content preserved</p>:<div className="workspace-diff"><pre>{file.before||'(absent)'}</pre><pre>{file.after||'(absent)'}</pre></div>}</details>)}{!preview.changes.length&&<p>No file changes.</p>}{error&&<p className="error-inline" role="alert">{error}</p>}<div className="button-row"><button className="primary-button" disabled={busy||!selected.length} onClick={()=>void run(async()=>{const recovery=await window.unreal.teamIntegrate(parent,reviewed,selected);setNotice(`Selected files integrated. Recovery checkpoint: ${recovery}`);setPreview(null)})}>Integrate selected files</button><button className="secondary-button" disabled={busy} onClick={()=>setPreview(null)}>Close review</button></div></>}</dialog>
 </section>
}
