import { useEffect,useState } from 'react'
import type { PlanningState,TaskPlan } from '../shared/planning'
import type { ModelCapabilities } from '../shared/model-capabilities'
import { TaskTeamControls } from './TaskTeams'
import { defaultTeamOptions } from '../shared/teams'
import { TeamPreferencesPanel } from './TeamPreferencesPanel'
import { BackgroundJobsPanel } from './BackgroundJobsPanel'

export function TaskControlPage({sessionId}:{sessionId:string|null}) {
  const [state,setState]=useState<PlanningState>({version:1,revisions:[]}),[caps,setCaps]=useState<ModelCapabilities|null>(null),[plan,setPlan]=useState({objective:'',body:'',acceptance:'',milestones:''}),[goal,setGoal]=useState({objective:'',requestLimit:50,tokenLimit:250000,elapsedMinutes:30}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<'ask'|'agent'>('ask')
  useEffect(()=>{let live=true;setState({version:1,revisions:[]});setError('');if(sessionId)void Promise.all([window.unreal.planning(sessionId),window.unreal.modelCapabilities(sessionId)]).then(([value,capabilities])=>{if(!live)return;setState(value);setCaps(capabilities);if(value.plan)setPlan({objective:value.plan.objective,body:value.plan.body,acceptance:value.plan.acceptance.join('\n'),milestones:value.plan.milestones.map(x=>x.text).join('\n')});if(value.goal)setGoal(value.goal)}).catch(reason=>{if(live)setError(String(reason))});return()=>{live=false}},[sessionId])
  const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await work();if(sessionId)setState(await window.unreal.planning(sessionId))}catch(reason){setError(String(reason))}finally{setBusy(false)}}
  if(!sessionId)return <div className="page-content"><h1>Task controls</h1><p>Create or open a session to manage its plan and goals.</p><TeamPreferencesPanel/></div>
  const lines=(value:string)=>value.split('\n').map(x=>x.trim()).filter(Boolean)
  return <div className="page-content task-controls-page"><h1>Task controls</h1><p>Plan revisions, bounded objectives and specialists for the selected conversation.</p>{error&&<p role="alert" className="error-inline">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <section className="settings-section"><h2>Plan · revision {state.plan?.revision||0}</h2><label>Objective<input value={plan.objective} onChange={e=>setPlan({...plan,objective:e.target.value})}/></label><label>Plan<textarea rows={8} value={plan.body} onChange={e=>setPlan({...plan,body:e.target.value})}/></label><label>Milestones · one per line<textarea value={plan.milestones} onChange={e=>setPlan({...plan,milestones:e.target.value})}/></label><label>Acceptance criteria · one per line<textarea value={plan.acceptance} onChange={e=>setPlan({...plan,acceptance:e.target.value})}/></label>
    <div className="button-row"><button disabled={busy} onClick={()=>void run(()=>window.unreal.planSave(sessionId,{objective:plan.objective,body:plan.body,acceptance:lines(plan.acceptance),milestones:lines(plan.milestones).map((text,index)=>({id:`milestone-${index+1}`,text,state:'pending',evidence:[]}))}))}>Save plan revision</button><select aria-label="Plan execution mode" value={mode} onChange={e=>setMode(e.target.value as 'ask'|'agent')}><option value="ask">Ask · approve actions</option><option value="agent">Agent · existing grants</option></select><button className="primary-button" disabled={busy||!state.plan||plan.objective!==state.plan.objective||plan.body!==state.plan.body||plan.acceptance!==state.plan.acceptance.join('\n')||plan.milestones!==state.plan.milestones.map(x=>x.text).join('\n')} onClick={()=>void run(()=>window.unreal.planImplement(sessionId,state.plan!.revision,mode))}>Implement this plan</button></div>
    <details><summary>Earlier revisions ({state.revisions.length})</summary>{state.revisions.map(item=><article key={item.revision}><strong>Revision {item.revision} · {item.updatedAt}</strong><pre>{item.body}</pre></article>)}</details></section>
    <section className="settings-section"><h2>Persistent objective · {state.goal?.state||'not set'}</h2><label>Goal<textarea value={goal.objective} onChange={e=>setGoal({...goal,objective:e.target.value})}/></label>{(['requestLimit','tokenLimit','elapsedMinutes'] as const).map(name=><label key={name}>{name==='requestLimit'?'Model request limit':name==='tokenLimit'?'Reported token limit':'Active minutes'}<input type="number" min={1} value={goal[name]} onChange={e=>setGoal({...goal,[name]:Number(e.target.value)})}/></label>)}<p>In-flight requests may exceed the reported token limit. Restart requires explicit resumption.</p><div className="button-row"><button disabled={busy||state.goal?.state==='running'} onClick={()=>void run(()=>window.unreal.goalSave(sessionId,goal))}>Save paused objective</button>{(['resume','pause','complete'] as const).map(action=><button key={action} disabled={busy||!state.goal} onClick={()=>void run(()=>window.unreal.goalAction(sessionId,action))}>{action==='complete'?'Mark verified complete':action==='resume'?'Resume':'Pause'}</button>)}</div>{state.goal&&<p>{state.goal.requests} requests · {state.goal.tokens.toLocaleString()} tokens · {Math.round(state.goal.elapsedMs/60000)} min · {state.goal.message}</p>}</section>
    <section className="settings-section"><h2>Model controls</h2><p>{caps?.provider} · {caps?.model}</p><p>{caps?.message}</p><div className="button-row"><button disabled={busy||!caps?.fast} onClick={()=>void run(async()=>{const result=await window.unreal.command({name:'fast',args:'',sessionId});setNotice(result.message||'Updated')})}>Toggle Fast</button><select aria-label="Reasoning effort" defaultValue="" disabled={busy||!caps?.reasoning.length} onChange={e=>void run(async()=>{const result=await window.unreal.command({name:'reasoning',args:e.target.value,sessionId});setNotice(result.message||'Updated')})}><option value="" disabled>Choose reasoning effort</option>{caps?.reasoning.map(value=><option key={value}>{value}</option>)}</select></div></section>
    <TaskTeamControls sessionId={sessionId} draft={defaultTeamOptions} onDraft={()=>{}}/>
    <TeamPreferencesPanel/>
    <BackgroundJobsPanel sessionId={sessionId}/>
  </div>
}
