import { useEffect, useState } from 'react'
import type { TaskWorkspace, WorkspacePreview } from '../shared/task-workspaces'
export function TaskWorkspaceReview({ onSource }: { onSource(): void }) {
  const [tasks, setTasks] = useState<TaskWorkspace[]>([]), [preview, setPreview] = useState<WorkspacePreview | null>(null), [selected, setSelected] = useState<string[]>([])
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('')
  const refresh = () => window.unreal.taskWorkspaces().then(setTasks).catch(reason => setError(String(reason)))
  useEffect(() => { void refresh(); return window.unreal.onWorkflowChanged(() => { void refresh() }) }, [])
  const inspect = async (id: string) => { setBusy(true); setError(''); try { if(tasks.find(task=>task.id===id)?.state==='archived'){if(!await window.unreal.workspaceRestore(id))return;await refresh()} const value = await window.unreal.workspacePreview(id); setPreview(value); setSelected([]) } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const integrate = async () => { if (!preview) return; setBusy(true); setError(''); try { const recovery = await window.unreal.workspaceIntegrate(preview.workspace.id, selected); setNotice(`Integrated selected files. Recovery checkpoint: ${recovery}`); setPreview(await window.unreal.workspacePreview(preview.workspace.id)); setSelected([]); await refresh() } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const retain = async () => { if (!preview) return; setBusy(true); setError(''); try { await window.unreal.workspaceRetain(preview.workspace.id); setNotice('Changes retained in the isolated task. The original project was not changed.'); setPreview(await window.unreal.workspacePreview(preview.workspace.id)); await refresh() } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const archive=async()=>{if(!preview)return;setBusy(true);setError('');try{if(!await window.unreal.workspaceArchive(preview.workspace.id))return;setPreview(null);await refresh();setNotice('Workspace archived. Its snapshot, branch and session history are retained.')}catch(reason){setError(String(reason))}finally{setBusy(false)}}
  return <section className="task-workspace-review"><div className="page-heading"><div><h2>Isolated tasks</h2><p>Review task changes against the original project before integration.</p></div><div className="button-row"><button className="secondary-button" onClick={onSource}>Source project and recovery</button><button className="secondary-button" onClick={() => void refresh()}>Refresh tasks</button></div></div>{error && <p className="error-inline" role="alert">{error}</p>}{notice && <p className="success-text">{notice}</p>}
    <div className="workspace-task-list">{tasks.filter(task => task.sessionId).map(task => <button className="secondary-button" key={task.id} disabled={busy} onClick={() => void inspect(task.id)}>{task.title} · {task.state}{task.state==='archived'?' · Restore…':''}</button>)}{!tasks.some(task => task.sessionId) && <p>No isolated tasks yet.</p>}</div>
    {preview && <><p><strong>{preview.workspace.branch}</strong> · {preview.workspace.path}</p>{Object.keys(preview.omitted).length > 0 && <details><summary>Capture omissions ({Object.keys(preview.omitted).length})</summary><pre>{JSON.stringify(preview.omitted, null, 2)}</pre></details>}{preview.changes.map(change => <details className="workspace-change" key={change.path}><summary><label><input type="checkbox" disabled={busy || change.conflict} checked={selected.includes(change.path)} onChange={event => setSelected(value => event.target.checked ? [...value, change.path] : value.filter(path => path !== change.path))}/>{change.path}</label> · {change.change}{change.conflict ? ' · Conflict: later project edits or uncaptured content' : ''}</summary>{change.binary ? <p>Binary contents will be restored exactly. Text preview unavailable.</p> : <div className="workspace-diff"><pre>{change.before || '(missing)'}</pre><pre>{change.after || '(missing)'}</pre></div>}</details>)}{!preview.changes.length && <p>No remaining task changes.</p>}<button className="primary-button" disabled={busy || !selected.length || preview.workspace.state === 'running'} onClick={() => void integrate()}>Integrate selected files</button></>}
    {preview?.workspace.state==='integrated'&&<button className="secondary-button" disabled={busy} onClick={()=>void archive()}>Archive integrated workspace…</button>}
    {preview && <button className="secondary-button" disabled={busy || preview.workspace.state === 'running'} onClick={() => void retain()}>Keep task changes and finish review</button>}
  </section>
}
