import { useEffect,useState } from 'react'
import { defaultTeamPreferences,type TeamPreferences,type RoleProfile } from '../shared/teams'
export function TeamPreferencesPanel(){
  const [value,setValue]=useState<TeamPreferences>(structuredClone(defaultTeamPreferences)),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{let live=true;void window.unreal.teamPreferences().then(next=>{if(live)setValue(next)}).catch(reason=>{if(live)setError(String(reason))});return()=>{live=false}},[])
  const profile=(role:RoleProfile['role'],patch:Partial<RoleProfile>)=>setValue(current=>({...current,profiles:current.profiles.map(item=>item.role===role?{...item,...patch}:item)}))
  return <section className="settings-section"><h2>Project specialist defaults</h2><p>Applies to new tasks. Automatic delegates only within the selected task's limits and permissions.</p><label>New task delegation<select aria-label="Project delegation policy" value={value.options.policy||'off'} onChange={e=>setValue({...value,options:{...value.options,policy:e.target.value as 'off'|'manual'|'automatic',allowSpecialists:e.target.value!=='off'}})}><option value="off">Off</option><option value="manual">Manual</option><option value="automatic">Automatic · project opt-in</option></select></label>
  {value.profiles.map(item=><details key={item.role}><summary>{item.role} · {item.provider==='inherit'?'Parent provider/model':`${item.provider}/${item.model}`}</summary><label>Description<input value={item.description} onChange={e=>profile(item.role,{description:e.target.value})}/></label><label>Instructions<textarea value={item.instructions} onChange={e=>profile(item.role,{instructions:e.target.value})}/></label><label>Provider<select value={item.provider} onChange={e=>profile(item.role,{provider:e.target.value as RoleProfile['provider']})}>{['inherit','openai-codex','openai','anthropic','openrouter','fireworks','ollama','openai-compatible'].map(provider=><option key={provider}>{provider}</option>)}</select></label><label>Model<input disabled={item.provider==='inherit'} value={item.model} onChange={e=>profile(item.role,{model:e.target.value})}/></label><label>Local / custom endpoint<input disabled={item.provider==='inherit'} value={item.baseUrl||''} onChange={e=>profile(item.role,{baseUrl:e.target.value})} placeholder="http://localhost:1234/v1"/></label><label>Reasoning effort<select value={item.thinkingLevel} onChange={e=>profile(item.role,{thinkingLevel:e.target.value})}><option value="">Inherit</option>{['low','medium','high','xhigh','max'].map(effort=><option key={effort}>{effort}</option>)}</select></label><p>Role limits · zero inherits the task budget</p>{(['modelRequestLimit','tokenLimit','elapsedMinutes'] as const).map(name=><label key={name}>{name}<input type="number" min={0} value={item.limits?.[name]||0} onChange={e=>profile(item.role,{limits:{modelRequestLimit:0,tokenLimit:0,elapsedMinutes:0,...item.limits,[name]:Number(e.target.value)}})}/></label>)}<label>Additional disabled tools · one per line<textarea value={item.disallowedTools.join('\n')} onChange={e=>profile(item.role,{disallowedTools:e.target.value.split('\n').filter(Boolean)})}/></label></details>)}
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={()=>{setBusy(true);setError('');void window.unreal.teamPreferencesSave(value).then(next=>{setValue(next);setNotice('Project defaults saved. Existing tasks retain their settings.')}).catch(reason=>setError(String(reason))).finally(()=>setBusy(false))}}>Save project defaults</button></section>
}
