import { useCallback, useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import type { Provider, SessionInfo } from '../shared/api'
import { defaultTeamOptions, type TeamOptions } from '../shared/teams'
import { TaskTeamControls } from './TaskTeams'
import { SavedWorkflows } from './SavedWorkflows'
import type { ContextSelection, ContextView, HandoffPreview, QueueSnapshot, SearchHit } from '../shared/workflow'

const api = window.unreal
const providers: Array<[Provider, string]> = [['openai-codex', 'Codex subscription'], ['openai', 'OpenAI API'], ['anthropic', 'Claude API'], ['ollama', 'Ollama'], ['openai-compatible', 'Local compatible'], ['openrouter', 'OpenRouter'], ['fireworks', 'Fireworks']]
const lines = (value: string): string[] => value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)

export function WorkflowPage({ project, sessionId, sessions, onOpen }: { project: string; sessionId: string | null; sessions: SessionInfo[]; onOpen: (project: string, sessionId: string, sequence?: number) => Promise<void> }): ReactNode {
  const [tab, setTab] = useState('queue')
  const [queue, setQueue] = useState<QueueSnapshot | null>(null)
  const [prompt, setPrompt] = useState('')
  const [taskOptions,setTaskOptions] = useState<TeamOptions>({ ...defaultTeamOptions })
  const [editing, setEditing] = useState('')
  const [editText, setEditText] = useState('')
  const [context, setContext] = useState<ContextView | null>(null)
  const [draft, setDraft] = useState<ContextSelection>({ pinned: [], attached: [], excluded: [], summary: '' })
  const [pinned, setPinned] = useState(''), [attached, setAttached] = useState(''), [excluded, setExcluded] = useState('')
  const [handoff, setHandoff] = useState<HandoffPreview | null>(null)
  const [source, setSource] = useState(sessionId || '')
  const [summary, setSummary] = useState('')
  const [provider, setProvider] = useState<Provider>('openai-codex'), [model, setModel] = useState(''), [baseUrl, setBaseUrl] = useState('')
  const [models, setModels] = useState<string[]>([])
  const [query, setQuery] = useState(''), [allProjects, setAllProjects] = useState(false), [searchSession, setSearchSession] = useState('')
  const [hits, setHits] = useState<SearchHit[]>([]), [searched, setSearched] = useState(false)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const refreshQueue = useCallback(async () => setQueue(await api.queueSnapshot()), [])
  useEffect(() => {
    void refreshQueue().catch((reason) => setError(String(reason)))
    return api.onWorkflowChanged((path) => { if (path === project) void refreshQueue().catch((reason) => setError(String(reason))) })
  }, [project, refreshQueue])
  const run = async (work: () => Promise<unknown>): Promise<void> => {
    setBusy(true); setError(''); setNotice('')
    try { await work() } catch (reason) { setError(String(reason)) } finally { setBusy(false) }
  }
  const loadContext = async (): Promise<void> => {
    const view = await api.contextView(sessionId || 'draft')
    setContext(view); setDraft(view.selection); setPinned(view.selection.pinned.join('\n')); setAttached(view.selection.attached.join('\n')); setExcluded(view.selection.excluded.join('\n'))
  }
  useEffect(() => { if (tab === 'context') void run(loadContext) }, [tab, sessionId])
  const move = (id: string, delta: number): void => {
    const ids = queue?.tasks.filter((task) => task.state === 'pending').map((task) => task.id) || []
    const index = ids.indexOf(id), target = index + delta
    if (index < 0 || target < 0 || target >= ids.length) return
    ;[ids[index], ids[target]] = [ids[target], ids[index]]
    void run(async () => setQueue(await api.queueReorder(ids)))
  }
  return <div className="page-content workflow-page"><div className="page-heading"><div><h1>Workflow</h1><p>Control task order, context, and continuation across providers.</p></div></div>
    <div className="workflow-tabs" role="tablist">{['queue', 'context', 'handoff', 'search', 'saved'].map((name) => <button key={name} role="tab" aria-selected={tab === name} className={tab === name ? 'selected' : ''} onClick={() => setTab(name)}>{name === 'queue' ? 'Task queue' : name === 'context' ? 'Context' : name === 'handoff' ? 'Provider handoff' : name === 'search' ? 'Conversation search' : 'Saved workflows'}</button>)}</div>
    {error && <p className="error-inline" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    {tab === 'saved' && <SavedWorkflows sessionId={sessionId} sessions={sessions} onOpen={id=>void onOpen(project,id)}/>}
    {tab === 'queue' && <section><div className="review-actions"><strong>{queue?.paused ? 'Queue paused' : 'Queue enabled'}</strong><button className="primary-button" disabled={busy} onClick={() => void run(async () => setQueue(await api.queuePause(!queue?.paused)))}>{queue?.paused ? 'Resume queue' : 'Pause queue'}</button></div><p>One queued task runs at a time in this project. Other open projects can run concurrently. Failures and required input pause advancement; reopening the app requires Resume.</p><textarea aria-label="New queued task" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Describe a task to queue…"/><TaskTeamControls draft={taskOptions} onDraft={setTaskOptions}/><button className="secondary-button" disabled={busy || !prompt.trim()} onClick={() => void run(async () => { setQueue(await api.queueAdd(prompt,taskOptions)); setPrompt(''); setTaskOptions({...defaultTeamOptions}) })}>Add task</button>
      <div className="queue-list">{queue?.tasks.map((task) => <article className="queue-card" key={task.id}><div className="section-heading"><strong>{task.state.replaceAll('_', ' ')}</strong><small>{task.config.provider} · {task.config.model}</small></div>{editing === task.id ? <><textarea aria-label="Edit queued task" value={editText} onChange={(event) => setEditText(event.target.value)}/><button disabled={busy || !editText.trim()} onClick={() => void run(async () => { setQueue(await api.queueEdit(task.id, editText)); setEditing('') })}>Save task</button></> : <p>{task.prompt}</p>}{task.source && <p><a href={task.source.url} target="_blank" rel="noreferrer">GitHub {task.source.kind} #{task.source.number}</a></p>}{task.message && <p className="muted-copy">{task.message}</p>}<div className="review-actions">{task.sessionId && <button className="secondary-button" onClick={() => void run(() => onOpen(project, task.sessionId!))}>Open session</button>}{task.state === 'pending' && <><button onClick={() => { setEditing(task.id); setEditText(task.prompt) }}>Edit</button><button aria-label="Move task up" onClick={() => move(task.id, -1)}>↑</button><button aria-label="Move task down" onClick={() => move(task.id, 1)}>↓</button></>}{['pending', 'starting', 'running', 'waiting_input', 'waiting_review'].includes(task.state) ? <button disabled={busy} onClick={() => void run(async () => setQueue(await api.queueAction(task.id, 'cancel')))}>Cancel</button> : <>{task.state !== 'completed' && <button disabled={busy} onClick={() => void run(async () => setQueue(await api.queueAction(task.id, 'retry')))}>{task.sessionId ? 'Retry as new session' : 'Retry task'}</button>}<button disabled={busy} onClick={() => void run(async () => setQueue(await api.queueAction(task.id, 'remove')))}>Remove from queue</button></>}</div></article>)}</div></section>}
    {tab === 'context' && <section><h2>{sessionId ? 'Selected session context' : 'Context for the next session'}</h2><p>Pins and exclusions apply to this project. Attachments and the editable summary belong to the selected session. Exclusions control automatic context and ProjectSearch, not filesystem permissions or manually requested shell commands.</p><div className="workflow-columns"><label>Pinned project files · one relative path per line<textarea value={pinned} onChange={(event) => setPinned(event.target.value)}/></label><label>Session attachments · one relative path per line<textarea value={attached} onChange={(event) => setAttached(event.target.value)}/></label><label>Excluded files or folders · one relative path per line<textarea value={excluded} onChange={(event) => setExcluded(event.target.value)}/></label></div><label>Context summary<textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} placeholder="Review and save a summary for future messages."/></label><div className="review-actions"><button className="primary-button" disabled={busy} onClick={() => void run(async () => { await api.updateContext(sessionId || 'draft', { pinned: lines(pinned), attached: lines(attached), excluded: lines(excluded), summary: draft.summary }); await loadContext(); setNotice('Context saved for future messages.') })}>Save context</button>{sessionId && <button disabled={busy} onClick={() => void run(async () => { const preview = await api.handoffPreview(sessionId); setDraft({ ...draft, summary: preview.summary }); setNotice('Draft prepared from recorded history. Review and save it before use.') })}>Draft summary from history</button>}</div>
      {context && <><p>Selected references: approximately {context.estimatedTokens.toLocaleString()} tokens (text-length estimate). Latest provider-reported input: {context.latestInput?.toLocaleString() ?? 'unknown'}; context limit: {context.contextLimit?.toLocaleString() ?? 'unknown'}.</p><table><thead><tr><th>File</th><th>Role</th><th>Included</th></tr></thead><tbody>{context.files.map((file) => <tr key={file.path}><td>{file.path}</td><td>{file.kind}</td><td>{file.included ? `${file.bytes.toLocaleString()} bytes` : file.reason}</td></tr>)}</tbody></table><details><summary>Persistent project instructions</summary><pre>{context.instructions || 'No additional project instructions.'}</pre></details><details><summary>Prepared reference context</summary><pre>{context.text || 'No selected reference context.'}</pre></details></>}
    </section>}
    {tab === 'handoff' && <section><h2>Continue with another provider</h2><p>Finish or stop current project operations first. The original session and its usage remain available. Review the summary before starting a new linked session.</p><label>Source session<select value={source} onChange={(event) => { setSource(event.target.value); setHandoff(null) }}><option value="">Choose a session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.title}</option>)}</select></label><button className="secondary-button" disabled={busy || !source} onClick={() => void run(async () => { const preview = await api.handoffPreview(source); setHandoff(preview); setSummary(preview.summary); setProvider(preview.config.provider); setModel(preview.config.model); setBaseUrl(preview.config.baseUrl) })}>Prepare handoff</button>{handoff && <><div className="workflow-columns"><label>Destination provider<select value={provider} onChange={(event) => { setProvider(event.target.value as Provider); setModel(''); setBaseUrl(''); setModels([]) }}>{providers.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Destination model<input list="handoff-models" value={model} onChange={(event) => setModel(event.target.value)}/><datalist id="handoff-models">{models.map((name) => <option key={name} value={name}/>)}</datalist></label><label>Endpoint (optional)<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder={provider === 'ollama' ? 'http://localhost:11434/v1' : 'Provider default'}/></label></div>{['ollama', 'openai-compatible'].includes(provider) && <button disabled={busy} onClick={() => void run(async () => setModels(await api.discoverModels(provider, baseUrl)))}>Discover local models</button>}<label>Reviewed handoff summary<textarea className="handoff-summary" value={summary} onChange={(event) => setSummary(event.target.value)}/></label><button className="primary-button" disabled={busy || !model.trim() || !summary.trim()} onClick={() => void run(async () => { const result = await api.handoffStart(source, summary, { provider, model: model.trim(), baseUrl, thinkingLevel: handoff.config.thinkingLevel }); await onOpen(project, result.sessionId) })}>Start continuation</button></>}</section>}
    {tab === 'search' && <section><h2>Search recorded conversations</h2><p>Search stays on this computer and uses cached history. Results may be incomplete while a project is syncing. Up to 200 matching events are shown.</p><div className="review-actions"><input aria-label="Search conversation content" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Message, tool output, or changed filename"/><select aria-label="Search session filter" value={searchSession} onChange={(event) => setSearchSession(event.target.value)}><option value="">All sessions</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.title}</option>)}</select><label><input type="checkbox" checked={allProjects} onChange={(event) => setAllProjects(event.target.checked)}/> All indexed projects</label><button className="primary-button" disabled={busy || !query.trim()} onClick={() => void run(async () => { setHits(await api.searchHistory(query, searchSession || undefined, allProjects)); setSearched(true) })}>Search</button></div>{hits.map((hit) => <button className="search-hit" key={`${hit.project}:${hit.sessionId}:${hit.seq}`} onClick={() => void run(() => onOpen(hit.project, hit.sessionId, hit.seq))}><strong>{hit.project.split(/[\\/]/).at(-1)} · {hit.sessionId.slice(0, 8)} · event {hit.seq}</strong><small>{hit.recordedAt ? new Date(hit.recordedAt).toLocaleString() : hit.kind}</small><p>{hit.snippet}</p></button>)}{searched && !hits.length && <p>No matching indexed events.</p>}</section>}
  </div>
}
