import { useEffect, useLayoutEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { ChevronDown, CircleHelp, RotateCcw } from 'lucide-react'
import { motion } from 'motion/react'
import type { AgentEvent,SessionInfo } from '../shared/api'
import type { ConversationUI, QuestionAnswer, QuestionRequest, WorkSummary, WorkView } from '../shared/activity'
import type { ParsedEntry } from './chat-events'
import { spatial,instant,effects } from './motion'
import { ProgressIndicator } from './ProgressIndicator'
import { useReducedMotion } from './useReducedMotion'

const api=window.unreal
const emptyUI=():ConversationUI=>({expanded:{},drafts:{}})
export function useWorkView(id:string|undefined,events:AgentEvent[]){
 const [view,setView]=useState<WorkView>(),[ui,setUI]=useState<ConversationUI>(emptyUI),[error,setError]=useState(''),[loaded,setLoaded]=useState(false)
 const selection=useRef({id,generation:0,request:0});if(selection.current.id!==id)selection.current={id,generation:selection.current.generation+1,request:0}
 const first=events.find(e=>e.seq>0)?.seq,last=events.filter(e=>e.seq>0).at(-1)?.seq
 const refresh=()=>{if(!id)return;const snapshot={...selection.current,request:++selection.current.request};void api.workView(id,{...(first?{from:first}:{}),...(last?{to:last}:{})}).then(value=>{if(selection.current.id===id&&selection.current.generation===snapshot.generation&&selection.current.request===snapshot.request){setView(value);setError('')}}).catch(e=>{if(selection.current.generation===snapshot.generation&&!String(e).includes('cancelled'))setError(String(e))})}
 useEffect(()=>{let live=true;setView(undefined);setUI(emptyUI());setLoaded(false);setError('');if(id)void api.conversationUI(id).then(value=>{if(live){setUI(value);setLoaded(true)}}).catch(e=>{if(live)setError(String(e))});else setLoaded(true);return()=>{live=false;selection.current.generation++}},[id])
 useEffect(()=>{const timer=setTimeout(refresh,100),interval=setInterval(refresh,2000);return()=>{clearTimeout(timer);clearInterval(interval)}},[id,first,last])
 const save=(patch:Partial<ConversationUI>)=>{setUI(current=>({expanded:{...current.expanded,...patch.expanded},drafts:{...current.drafts,...patch.drafts}}));if(id)void api.saveConversationUI(id,patch).catch(e=>setError(`Draft could not be saved: ${e}`))}
 return {view,ui,save,refresh,error,loaded,ready:loaded&&!!view&&view.cache.latest>=(last||0)}
}
export type WorkController=ReturnType<typeof useWorkView>
function label(w:WorkSummary){if(w.state==='waiting_input')return 'Waiting for your answer';if(w.state==='running')return 'Working…';if(w.state==='failed')return 'Failed';if(w.state==='stopped')return 'Stopped';if(w.state==='interrupted')return 'Interrupted';if(w.elapsedMs===undefined)return 'Worked · timing unavailable';if(w.elapsedMs<1000)return 'Worked for '+Math.round(w.elapsedMs)+' ms';const seconds=Math.floor(w.elapsedMs/1000),m=Math.floor(seconds/60);return `Worked for ${m?`${m}m `:''}${seconds%60}s${w.state==='completed_with_warnings'?' · warnings':''}`}
function WorkDisclosure({work,expanded,onChange,children,disabled,animateProgress}:{work:WorkSummary;expanded?:boolean;onChange(value:boolean):void;children:ReactNode;disabled?:boolean;animateProgress:boolean}){
 const ref=useRef<HTMLElement>(null),reduced=useReducedMotion(),[held,setHeld]=useState(false)
 const wasRunning=useRef(work.open),root=ref.current,scroller=root?.closest('.chat-scroll'),protect=wasRunning.current&&!work.open&&!!root&&!!scroller&&(root.contains(document.activeElement)||scroller.scrollHeight-scroller.scrollTop-scroller.clientHeight>60),open=expanded??(work.open||held||protect)
 useLayoutEffect(()=>{if(wasRunning.current&&!work.open&&expanded===undefined){const root=ref.current,scroller=root?.closest('.chat-scroll');if(root&&scroller&&(root.contains(document.activeElement)||scroller.scrollHeight-scroller.scrollTop-scroller.clientHeight>60))setHeld(true)}wasRunning.current=work.open},[work.open,expanded])
 return <section className={`work-section ${open?'expanded':''}`} ref={ref} data-work-id={work.id}><button className="work-disclosure" disabled={disabled} aria-expanded={open} onClick={()=>{setHeld(false);onChange(!open)}}><ProgressIndicator animate={animateProgress} state={work.state==='running'?'running':work.state==='waiting_input'?'waiting':work.state==='failed'?'error':work.state==='stopped'||work.state==='interrupted'?'stopped':work.state==='completed'?'success':'idle'}/><span>{label(work)}</span><motion.span initial={false} animate={{rotate:open?0:-90}} transition={reduced?instant:spatial.fast}><ChevronDown size={15}/></motion.span></button><motion.div className="work-content" hidden={!open} initial={false} animate={{opacity:open?1:0}} transition={reduced?instant:effects.fast}>{children}</motion.div></section>
}
function QuestionCard({q,controller,online,sessionActive,onStop,answerSequence}:{q:QuestionRequest;controller:WorkController;online:boolean;sessionActive:boolean;onStop():void;answerSequence?:number}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[summaryOpen,setSummaryOpen]=useState(false)
 const stored=controller.ui.drafts[q.id],draft=stored?.revision===q.revision?stored:undefined
 const [identity]=useState(()=>crypto.randomUUID()),answers:QuestionAnswer[]=draft?.answers||q.questions.map(item=>({questionId:item.id,text:''})),submissionId=draft?.submissionId||identity
 const answered=q.state==='answered',cancelled=q.state==='cancelled',interrupted=q.state==='interrupted'
 const update=(index:number,patch:Partial<QuestionAnswer>)=>{const next=answers.map((a,i)=>i===index?{...a,...patch}:a);controller.save({drafts:{[q.id]:{revision:q.revision,submissionId,answers:next}}})}
 const submit=async()=>{if(busy)return;setBusy(true);setError('');controller.save({drafts:{[q.id]:{revision:q.revision,submissionId,answers}}});try{await api.answerQuestion({sessionId:q.sessionId,workspaceId:q.workspaceId,id:q.id,revision:q.revision,submissionId,answers,resume:interrupted});controller.refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const complete=answers.length===q.questions.length&&answers.every(a=>a.choiceId||a.text?.trim())
 const dismiss=async()=>{setBusy(true);try{await api.dismissQuestion(q.sessionId,q.id);controller.refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <section id={`question-${q.id}`} className={`question-card ${q.state}`} aria-label={answered?'Answered questions':'Your input is needed'} tabIndex={-1} data-event-seq={q.seq}>
  {answerSequence&&<span data-event-seq={answerSequence} aria-hidden="true"/>}
  <header><CircleHelp size={19}/><strong>{answered?'Answers recorded':cancelled?'Question dismissed':q.mode==='background'?'A question for you':'Your input is needed'}</strong><span className="activity-badge">{busy?'Submitting…':q.state}</span></header>
  {answered?<><button className="question-summary" aria-expanded={summaryOpen} onClick={()=>setSummaryOpen(!summaryOpen)}>{q.questions.map(item=>{const a=q.answers?.find(a=>a.questionId===item.id),choice=item.choices?.find(c=>c.id===a?.choiceId);return <span key={item.id}><strong>{item.title}</strong><span>{choice?.label}{choice&&a?.text?' — ':''}{a?.text}</span></span>})}<ChevronDown size={16}/></button>{summaryOpen&&<p className="muted-copy">Accepted {new Date(q.updatedAt).toLocaleString()}. These answers do not change tool permissions.</p>}</>:cancelled?<p>{q.questions.map(item=>item.title).join(' · ')}</p>:<form onSubmit={event=>{event.preventDefault();void submit()}}>
   {q.questions.map((item,index)=><fieldset key={item.id} disabled={busy||!controller.loaded}><legend>{item.title}</legend>{item.choices?.map(choice=><label className={`question-choice ${answers[index]?.choiceId===choice.id?'selected':''}`} key={choice.id}><input type="radio" name={`${q.id}-${item.id}`} checked={answers[index]?.choiceId===choice.id} onChange={()=>update(index,{choiceId:choice.id})}/><span><strong>{choice.label}</strong>{choice.recommended&&<small className="recommendation">Recommended</small>}{choice.description&&<span>{choice.description}</span>}</span></label>)}<label className="question-free"><span>{item.choices?.length?'Or write your own answer':'Your answer'}</span><textarea aria-label={`Your answer: ${item.title}`} maxLength={8000} value={answers[index]?.text||''} onChange={event=>update(index,{text:event.target.value,choiceId:undefined})} rows={2}/></label></fieldset>)}
   <div className="question-actions"><button type="submit" className="primary-button" disabled={busy||!online||!complete||!controller.loaded}>{busy?'Submitting…':interrupted?'Answer and resume':'Submit answers'}</button>{q.mode==='required'?<button type="button" className="secondary-button" disabled={busy||!online} onClick={onStop}>Stop task</button>:<button type="button" className="text-button" disabled={busy||!online} onClick={()=>void dismiss()}>Dismiss</button>}</div>
   {!online&&<p className="muted-copy">Your draft stays here. Connect Docker to submit it.</p>}{interrupted&&online&&<p className="muted-copy">This task is interrupted. Submitting explicitly resumes it; paused queues still require Resume.</p>}
  </form>}{error&&<p className="error-inline" role="alert">{error}</p>}
 </section>
}
export function WorkConversation({entries,controller,session,online,renderEntry,onStop}:{entries:ParsedEntry[];controller:WorkController;session:SessionInfo|undefined;online:boolean;renderEntry(entry:ParsedEntry):ReactNode;onStop():void}){
 const [retryBusy,setRetryBusy]=useState(false),[retryError,setRetryError]=useState(''),retryIds=useRef(new Map<number,string>())
 const view=controller.view,works=view?.works||[]
 useEffect(()=>{if(controller.ready)window.dispatchEvent(new Event('unreal:work-ready'))},[view,controller.ready])
 const rows=useMemo(()=>{const statuses=new Map(view?.activity?.map(row=>[row.id,row.status]));return [...entries.filter(e=>e.kind!=='question'&&(!e.questionResponseId||!view?.questions.some(q=>q.id===e.questionResponseId))).map(entry=>{const status=statuses.get(entry.activityId||entry.id.replace(/^call:/,''));return {seq:entry.seq||Number(entry.id.split(':')[0])||0,entry:status&&entry.kind==='tool'?{...entry,status:status.replaceAll('_',' ')}:entry}}),...(view?.questions||[]).map(question=>({seq:question.seq,question}))].sort((a,b)=>a.seq-b.seq)},[entries,view])
 const parts:ReactNode[]=[];let group:ParsedEntry[]=[],current:WorkSummary|undefined,segment=0;const indicated=new Set<string>()
 const flush=()=>{if(!group.length)return;const chunk=group;group=[];const w=current;if(!w){parts.push(...chunk.map(e=><div key={e.id} data-event-seq={e.seq}>{(e.eventSequences||[]).filter(seq=>seq!==e.seq).map(seq=><span key={seq} data-event-seq={seq} aria-hidden="true"/>)}{renderEntry(e)}</div>));return}const animateProgress=w.id===works.at(-1)?.id&&!indicated.has(w.id);indicated.add(w.id);parts.push(<WorkDisclosure animateProgress={animateProgress} key={`${w.id}:${segment++}`} work={w} disabled={!controller.loaded} expanded={controller.ui.expanded[w.id]} onChange={value=>controller.save({expanded:{[w.id]:value}})}>{chunk.map(e=><div key={e.id} data-event-seq={e.seq}>{(e.eventSequences||[]).filter(seq=>seq!==e.seq).map(seq=><span key={seq} data-event-seq={seq} aria-hidden="true"/>)}{renderEntry(e)}</div>)}</WorkDisclosure>)}
 for(const row of rows){const work=works.find(w=>row.seq>=w.seq&&(!w.endSeq||row.seq<=w.endSeq));if(work?.id!==current?.id){flush();current=work}if('question'in row){flush();parts.push(<QuestionCard key={row.question.id} q={row.question} answerSequence={entries.find(e=>e.questionResponseId===row.question.id)?.seq} controller={controller} online={online} sessionActive={!!session?.active} onStop={onStop}/>);continue}const entry=row.entry;if(entry.kind==='user'||entry.kind==='status'&&entry.status==='error'||entry.phase==='final_answer'||(entry.id===work?.finalMessageId||work?.finalMessageIds?.includes(entry.id))){flush();parts.push(<div key={entry.id} data-event-seq={row.seq}>{renderEntry(entry)}</div>)}else group.push(entry)}flush()
 const failed=[...works].reverse().find(w=>w.state==='failed'&&w.failureSequence),latest=works.at(-1)
 if(latest?.open&&!indicated.has(latest.id))parts.push(<div className="work-pending" role="status" key={`pending:${latest.id}`}><ProgressIndicator state={latest.state==='waiting_input'?'waiting':'running'}/><span>{label(latest)}</span></div>)
 const retry=async()=>{if(!session||!failed?.failureSequence||retryBusy)return;const seq=failed.failureSequence;let id=retryIds.current.get(seq);if(!id){id=crypto.randomUUID();retryIds.current.set(seq,id)}setRetryBusy(true);setRetryError('');try{await api.retryResponse(session.id,seq,id);controller.refresh()}catch(e){setRetryError(String(e))}finally{setRetryBusy(false)}}
 return <><span hidden data-work-ready={controller.ready}/>{controller.error&&<p className="error-inline">{controller.error}</p>}{parts}{failed&&failed===latest&&<div className="response-recovery"><p>The response failed. Accepted answers and completed tool results remain in this conversation.</p><button className="secondary-button" disabled={!online||retryBusy} onClick={()=>void retry()}><RotateCcw size={15}/>{retryBusy?'Retrying…':'Retry response'}</button>{retryError&&<p className="error-inline" role="alert">{retryError}</p>}</div>}</>
}
