import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { randomUUID,createHash } from 'node:crypto'
import { promises as fs } from 'node:fs'
import { backendEnvironment } from './child-environment'
import { durableRoots } from './recovery-files'
import type { StorageItem } from '../shared/recovery'
const exec=promisify(execFile)
export interface RecoveryVolumes { existing(names:string[]):Promise<string[]>; export(volume:string,path:string):Promise<void>; import(path:string):Promise<string>; }
export class DockerRecoveryVolumes implements RecoveryVolumes {
 async modelStorage(volumes:string[]):Promise<StorageItem[]>{if(!volumes.length)return [];const image=await this.image(),result:StorageItem[]=[];for(const volume of volumes){const raw=await this.docker(['run','--rm','--network','none','--cap-drop=ALL','--entrypoint','python3','--mount',`type=volume,source=${volume},target=/state,readonly`,image,'-c','import os,json,hashlib\np="/state/model-cache"; size=0; h=hashlib.sha256()\nfor root,dirs,files in os.walk(p,followlinks=False):\n for name in sorted(dirs+files):\n  q=os.path.join(root,name);s=os.lstat(q);h.update((q+str(s.st_size)+str(s.st_mtime_ns)).encode());size+=s.st_size if not os.path.isdir(q) else 0\nprint(json.dumps(dict(bytes=size,digest=h.hexdigest())))']);const info=JSON.parse(raw);if(info.bytes)result.push({id:createHash('sha256').update(volume+info.digest).digest('hex'),path:`${volume}:/state/model-cache`,category:'models',bytes:info.bytes,removable:true,reason:'Downloaded model cache; models will download again when needed.'})}return result}
 async removeModelCache(volume:string):Promise<void>{if(!/^unrealcode-(?:eval-|restore-)?[a-f0-9-]{20,36}$/.test(volume))throw new Error('Invalid model-cache volume');await this.idle(volume);await this.docker(['run','--rm','--network','none','--cap-drop=ALL','--entrypoint','python3','--mount',`type=volume,source=${volume},target=/state`,await this.image(),'-c','import os,shutil\np="/state/model-cache"\nif os.path.islink(p): raise Exception("Cache root is a link")\nif os.path.isdir(p): shutil.rmtree(p)'])}
 private async docker(args:string[]):Promise<string>{const {stdout}=await exec('docker',args,{windowsHide:true,timeout:300000,maxBuffer:8*1024*1024,env:backendEnvironment()});return stdout.trim()}
 async existing(names:string[]):Promise<string[]>{if(!names.length)return [];const present=new Set((await this.docker(['volume','ls','--format','{{.Name}}'])).split('\n'));return names.filter(name=>present.has(name))}
 private async image():Promise<string>{const images=(await this.docker(['image','ls','--format','{{.Repository}}:{{.Tag}}','unrealcode'])).split('\n');const image=images.find(value=>/^unrealcode:[\w.-]+$/.test(value));if(!image)throw new Error('Prepare the UnrealCode Docker backend before backing up or restoring sessions');return image}
 private async idle(volume:string):Promise<void>{if(await this.docker(['ps','-q','--filter',`volume=${volume}`]))throw new Error('A saved-session volume is in use. Close other UnrealCode instances and retry.')}
 async export(volume:string,path:string):Promise<void>{await this.idle(volume);await fs.mkdir(path,{recursive:true});await this.copy(volume,path,false)}
 async import(path:string):Promise<string>{const volume=`unrealcode-restore-${randomUUID()}`;await this.docker(['volume','create',volume]);try{await this.copy(volume,path,true);return volume}catch(error){await this.docker(['volume','rm',volume]).catch(()=>{});throw error}}
 private async copy(volume:string,path:string,restore:boolean):Promise<void>{
  const script=`import os,shutil,stat,json\nsource,target=${restore?'"/backup","/state"':'"/state","/backup"'}\nallowed=${JSON.stringify(durableRoots)}\ndef copy(a,b):\n s=os.lstat(a)\n if stat.S_ISLNK(s.st_mode): raise Exception("Session backup contains a link")\n if stat.S_ISDIR(s.st_mode):\n  os.makedirs(b,exist_ok=True)\n  for name in os.listdir(a): copy(os.path.join(a,name),os.path.join(b,name))\n elif stat.S_ISREG(s.st_mode):\n  os.makedirs(os.path.dirname(b),exist_ok=True);shutil.copyfile(a,b)\n  if ${restore?'True':'False'} and a.startswith("/backup/desktop-config/"):\n   with open(b) as f: value=json.load(f)\n   value.update(mode="ask",teamEnabled=False,teamManaged=False,baseUrl="")\n   with open(b,"w") as f: json.dump(value,f)\n else: raise Exception("Unsupported session file")\n if ${restore?'True':'False'}: os.chown(b,10001,10001)\nfor name in allowed:\n a=os.path.join(source,name)\n if os.path.lexists(a):copy(a,os.path.join(target,name))\n`
  await this.docker(['run','--rm','--network','none','--cap-drop=ALL',...(restore?['--cap-add=CHOWN']:[]),'--security-opt=no-new-privileges','--user',restore?'0:0':'10001:10001','--entrypoint','python3','--mount',`type=volume,source=${volume},target=/state${restore?'':',readonly'}`,'--mount',`type=bind,source=${path},target=/backup${restore?',readonly':''}`,await this.image(),'-c',script])
 }
}
