import { join } from 'node:path'
import type { PlanningState,TaskPlan,Goal } from '../shared/planning'
import { atomicMetadata } from './atomic-metadata'
import { readBoundedJSON } from './bounded-file-read'
import {randomUUID} from 'node:crypto'

export class TaskPlanning {
  private tails=new Map<string,Promise<unknown>>()
  private resumed=new Set<string>()
  constructor(private directory:string){}
  active():string[]{return [...this.resumed]}
  private path(id:string){if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid session identity');return join(this.directory,`${id}.json`)}
  async read(id:string):Promise<PlanningState>{let state:PlanningState;try{state=await readBoundedJSON<PlanningState>(this.path(id),32*1024*1024)}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;state={version:1,revisions:[]}}
    if(state.version!==1||!Array.isArray(state.revisions))throw Error('Unsupported planning metadata')
    if(state.goal?.state==='running'&&!this.resumed.has(id)){state.goal.state='paused';state.goal.message='Application restarted. Review the objective and explicitly resume.'}return state}
  private mutate<T>(id:string,work:(state:PlanningState)=>T):Promise<T>{const next=(this.tails.get(id)||Promise.resolve()).catch(()=>{}).then(async()=>{const state=await this.read(id),result=work(state),encoded=JSON.stringify(state);if(Buffer.byteLength(encoded)>32*1024*1024)throw Error('Planning metadata exceeds its safe size limit');await atomicMetadata(this.path(id),encoded);return result});this.tails.set(id,next);void next.finally(()=>{if(this.tails.get(id)===next)this.tails.delete(id)}).catch(()=>{});return next}
  savePlan(id:string,input:Pick<TaskPlan,'objective'|'body'|'acceptance'|'milestones'>):Promise<TaskPlan>{
    if(!input||typeof input.objective!=='string'||!input.objective.trim()||input.objective.length>4000||typeof input.body!=='string'||input.body.length>64000||!Array.isArray(input.acceptance)||input.acceptance.length>50||input.acceptance.some(x=>typeof x!=='string'||x.length>2000)||!Array.isArray(input.milestones)||input.milestones.length>100||input.milestones.some(x=>!x||typeof x.id!=='string'||typeof x.text!=='string'||x.text.length>2000||!['pending','running','completed'].includes(x.state)||!Array.isArray(x.evidence)||x.evidence.length>100||x.evidence.some(e=>typeof e!=='string'||e.length>4000))||Buffer.byteLength(JSON.stringify(input))>512*1024)return Promise.reject(Error('Invalid plan; provide bounded objective, milestones and acceptance criteria'))
    return this.mutate(id,state=>{const used=new Set<string>();const milestones=input.milestones.map(item=>{const prior=state.plan?.milestones.find(old=>old.text===item.text&&!used.has(old.id));if(prior){used.add(prior.id);return structuredClone(prior)}return {...item,id:randomUUID()}});input={...input,milestones};if(state.plan&&JSON.stringify({objective:state.plan.objective,body:state.plan.body,acceptance:state.plan.acceptance,milestones:state.plan.milestones})===JSON.stringify(input))return state.plan;if(state.plan)state.revisions.push(state.plan);state.revisions=state.revisions.slice(-50);state.plan={...structuredClone(input),revision:(state.plan?.revision||0)+1,updatedAt:new Date().toISOString()};return state.plan})
  }
  approve(id:string,revision:number):Promise<TaskPlan>{return this.mutate(id,state=>{if(!state.plan||state.plan.revision!==revision)throw Error('The plan changed. Review the latest revision.');state.plan.approvedRevision=revision;return state.plan})}
  async saveAgentPlan(id:string,input:{objective:string;body:string;acceptance:string[];milestones:string[]}):Promise<TaskPlan>{
    if(!Array.isArray(input.milestones)||input.milestones.some(text=>typeof text!=='string'))throw Error('Plan milestones must be text')
    // Stable identities are reconciled inside savePlan's serialized transaction.
    return this.savePlan(id,{...input,milestones:input.milestones.map(text=>({id:randomUUID(),text,state:'pending',evidence:[]}))})
  }
  async progress(id:string,revision:number,milestoneId:string,status:'pending'|'running'|'completed',evidence:string[]):Promise<TaskPlan>{
    if(!['pending','running','completed'].includes(status)||!Array.isArray(evidence)||evidence.length>30||evidence.some(x=>typeof x!=='string'||!x.trim()||x.length>2000)||status==='completed'&&!evidence.length)throw Error('Completion needs bounded evidence')
    return this.mutate(id,state=>{if(!state.plan||state.plan.revision!==revision)throw Error('Plan revision changed; read it again');const milestone=state.plan.milestones.find(x=>x.id===milestoneId);if(!milestone)throw Error('Unknown milestone');milestone.state=status;milestone.evidence=[...evidence];state.plan.updatedAt=new Date().toISOString();return state.plan})
  }
  goal(id:string,input:Pick<Goal,'objective'|'requestLimit'|'tokenLimit'|'elapsedMinutes'>):Promise<Goal>{
    if(!input||typeof input.objective!=='string'||!input.objective.trim()||input.objective.length>8000||![input.requestLimit,input.tokenLimit,input.elapsedMinutes].every(x=>Number.isSafeInteger(x)&&x>0)||input.requestLimit>10000||input.tokenLimit>10000000||input.elapsedMinutes>1440)return Promise.reject(Error('Goals require an objective and positive request, token and time limits'))
    return this.mutate(id,state=>{if(state.goal?.state==='running')throw Error('Pause the active objective before replacing it');return state.goal={...input,state:'paused',requests:0,tokens:0,elapsedMs:0,lastSequence:0}})
  }
  goalAction(id:string,action:'resume'|'pause'|'complete'):Promise<Goal>{return this.mutate(id,state=>{if(!state.goal)throw Error('No objective has been set');if(action==='resume'){if(state.goal.state==='limited')throw Error('Revise the objective limits before resuming');this.resumed.add(id);state.goal.state='running'}else{this.resumed.delete(id);state.goal.state=action==='complete'?'completed':'paused'}return state.goal})}
  permit(id:string,requestId:string):Promise<void>{return this.mutate(id,state=>{const goal=state.goal;if(!goal||goal.state!=='running')throw Error('Goal is paused or its budget has been reached');if(goal.permits?.includes(requestId))return;if(goal.requests>=goal.requestLimit||goal.tokens>=goal.tokenLimit||goal.elapsedMs>=goal.elapsedMinutes*60000)throw Error('Goal budget reached');goal.permits=[...(goal.permits||[]),requestId];goal.requests++})}
  tick(id:string,elapsedMs:number):Promise<Goal|undefined>{return this.mutate(id,state=>{const goal=state.goal;if(!goal||goal.state!=='running')return goal;goal.elapsedMs+=Math.max(0,elapsedMs);if(goal.elapsedMs>=goal.elapsedMinutes*60000){goal.state='limited';goal.message='Goal elapsed-time limit reached';this.resumed.delete(id)}return goal})}
  consumeWorker(id:string,worker:string,sequence:number,tokens:number):Promise<Goal|undefined>{return this.mutate(id,state=>{const goal=state.goal;if(!goal||!['running','limited','paused'].includes(goal.state)||sequence<=(goal.workerSequences?.[worker]||0))return goal;goal.workerSequences||={};goal.workerSequences[worker]=sequence;goal.tokens+=Math.max(0,tokens);if(goal.tokens>=goal.tokenLimit){goal.state='limited';goal.message='Goal token limit reached, including specialist usage. In-flight requests may exceed it.';this.resumed.delete(id)}return goal})}
  complete(id:string,evidence:string[]):Promise<Goal>{return this.mutate(id,state=>{if(!state.goal||state.goal.state!=='running')throw Error('No active goal');if(!Array.isArray(evidence)||!evidence.length||evidence.length>30||evidence.some(x=>typeof x!=='string'||!x.trim()||x.length>4000))throw Error('Completion requires bounded verification evidence');state.goal.state='completed';state.goal.evidence=evidence;this.resumed.delete(id);return state.goal})}
  consume(id:string,sequence:number,requests:number,tokens:number,elapsedMs=0,requestId?:string):Promise<Goal|undefined>{return this.mutate(id,state=>{const goal=state.goal;if(!goal||sequence<=goal.lastSequence||requestId!==undefined&&!goal.permits?.includes(requestId))return goal;goal.lastSequence=sequence;goal.requests+=requests;goal.tokens+=tokens;goal.elapsedMs+=elapsedMs;if(goal.state!=='completed'&&(goal.requests>=goal.requestLimit||goal.tokens>=goal.tokenLimit||goal.elapsedMs>=goal.elapsedMinutes*60000)){goal.state='limited';goal.message='Goal budget reached. Already running requests may exceed the reported token limit.';this.resumed.delete(id)}return goal})}
}
